import type { DingGameModeDefinition } from "./types";
import { baseVisibleCommunity, standardDeal } from "./types";

export const GAME_MODE_DEFINITIONS: readonly DingGameModeDefinition[] = [
  {
    id: "ding",
    name: "Classic Ding",
    shortName: "Classic",
    summary: "The original cooperative hold'em ranking game.",
    detail: "Two private cards, five shared board cards, strongest poker hand wins.",
    tags: ["default", "balanced"],
    deal: standardDeal,
    score: "high",
  },
  {
    id: "draw-three",
    name: "Draw 3, Discard 1",
    shortName: "Draw 3",
    summary: "Every hand is dealt three cards and automatically keeps its best two-card start.",
    detail: "The discard happens before pre-flop so players still coordinate with two-card hands.",
    tags: ["swingy", "friendly"],
    deal: { ...standardDeal, holeCards: 3, keepCards: 2 },
    score: "high",
  },
  {
    id: "one-up",
    name: "One Up",
    shortName: "One Up",
    summary: "One card from every hand is public from the start.",
    detail: "The exposed card gives the table shared anchors without revealing the full hand.",
    tags: ["social", "information"],
    deal: { ...standardDeal, publicCards: 1 },
    score: "high",
  },
  {
    id: "open-book",
    name: "Open Book",
    shortName: "Open",
    summary: "Everyone's hole cards are public.",
    detail: "A low-bluff, high-coordination mode where disagreements are about interpretation.",
    tags: ["transparent", "fast"],
    deal: { ...standardDeal, publicCards: 2 },
    score: "high",
  },
  {
    id: "late-light",
    name: "Late Light",
    shortName: "Late",
    summary: "Hole cards become public at the river.",
    detail: "Hands stay private through turn, then every hole card is exposed at river before the final ranking.",
    tags: ["information", "river"],
    deal: { ...standardDeal, visibleHoleCards: { river: 2, reveal: 2 } },
    score: "high",
  },
  {
    id: "suit-showing",
    name: "Suit Showing",
    shortName: "Suits",
    summary: "Every hole-card suit is public, but ranks stay hidden.",
    detail: "The table sees suit texture from the deal while actual ranks remain private until reveal.",
    tags: ["information", "suits"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 },
      visibleHoleCardDetail: "suit",
    },
    score: "high",
  },
  {
    id: "rank-showing",
    name: "Rank Showing",
    shortName: "Ranks",
    summary: "Every hole-card rank is public, but suits stay hidden.",
    detail: "The table sees paired and high-card structure from the deal while exact suits remain private until reveal.",
    tags: ["information", "ranks"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 },
      visibleHoleCardDetail: "rank",
    },
    score: "high",
  },
  {
    id: "color-showing",
    name: "Color Showing",
    shortName: "Colors",
    summary: "Every hole-card color is public, but ranks and suits stay hidden.",
    detail: "The table sees red/black texture from the deal while exact ranks and suits remain private until reveal.",
    tags: ["information", "colors"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 },
      visibleHoleCardDetail: "color",
    },
    score: "high",
  },
  {
    id: "brightest-out",
    name: "Brightest Out",
    shortName: "Brightest",
    summary: "The highest hole card in every hand is public from the start.",
    detail: "Each hand exposes its brightest private card, giving the table a high-card anchor while the lower card stays hidden until reveal.",
    tags: ["information", "high-card"],
    deal: { ...standardDeal, publicCards: 1, publicCardSelection: "highest" },
    score: "high",
  },
  {
    id: "darkest-out",
    name: "Darkest Out",
    shortName: "Darkest",
    summary: "The lowest hole card in every hand is public from the start.",
    detail: "Each hand exposes its darkest private card, giving the table a low-card anchor while the higher card stays hidden until reveal.",
    tags: ["information", "low-card"],
    deal: { ...standardDeal, publicCards: 1, publicCardSelection: "lowest" },
    score: "high",
  },
  {
    id: "short-deck",
    name: "Short Deck",
    shortName: "Short",
    summary: "Cards two through five are removed before the deal.",
    detail: "Compressed ranks make strong hands common and hand reading more volatile.",
    tags: ["volatile", "compact"],
    deal: { ...standardDeal, deck: "short" },
    score: "high",
  },
  {
    id: "stripped",
    name: "Stripped",
    shortName: "Stripped",
    summary: "Only ranks 8 through ace are in the deck.",
    detail: "The deck compresses to twenty-eight high cards, making premium holdings and collisions common.",
    tags: ["deck", "compact"],
    deal: { ...standardDeal, deck: "stripped" },
    score: "high",
  },
  {
    id: "bottom-half",
    name: "Bottom Half",
    shortName: "Bottom",
    summary: "Only ranks two through nine are in the deck.",
    detail: "The deck removes broadway texture and makes low-rank board reading much sharper.",
    tags: ["deck", "low"],
    deal: { ...standardDeal, deck: "bottomHalf" },
    score: "high",
  },
  {
    id: "double-deck",
    name: "Double Deck",
    shortName: "Double",
    summary: "Two full decks are merged before the deal.",
    detail: "Duplicate identities can appear, increasing rank collisions and strange shared-outs.",
    tags: ["deck", "duplicates"],
    deal: { ...standardDeal, deck: "double" },
    score: "high",
  },
  {
    id: "triple-deck",
    name: "Triple Deck",
    shortName: "Triple",
    summary: "Three full decks are merged before the deal.",
    detail: "The enlarged deck makes exact duplicate cards possible while preserving cooperative ranking.",
    tags: ["deck", "duplicates"],
    deal: { ...standardDeal, deck: "triple" },
    score: "high",
  },
  {
    id: "half-deck",
    name: "Half Deck",
    shortName: "Half",
    summary: "A random twenty-six-card deck is used for the whole hand.",
    detail: "Half the deck is removed before dealing, creating a tight and unpredictable card pool.",
    tags: ["deck", "compact"],
    deal: { ...standardDeal, deck: "half" },
    score: "high",
  },
  {
    id: "pinochle",
    name: "Pinochle",
    shortName: "Pinochle",
    summary: "Ranks nine through ace appear twice in each suit.",
    detail: "A duplicated high-card deck creates compact, collision-heavy boards and hands.",
    tags: ["deck", "duplicates"],
    deal: { ...standardDeal, deck: "pinochle" },
    score: "high",
  },
  {
    id: "tarot",
    name: "Tarot",
    shortName: "Tarot",
    summary: "Arcana cards are mixed into the deck as wild high cards.",
    detail: "Two tarot-marked wild cards join the standard deck and can stand in for the best identity at showdown.",
    tags: ["deck", "wild"],
    deal: { ...standardDeal, deck: "tarot" },
    wildCards: { metas: ["tarot"] },
    score: "high",
  },
  {
    id: "suit-heavy",
    name: "Suit-Heavy",
    shortName: "Heavy",
    summary: "One suit is doubled before the deal.",
    detail: "Hearts are the current doubled suit, creating a flush-heavy deck while keeping normal cooperative ranking.",
    tags: ["deck", "suits"],
    deal: { ...standardDeal, deck: "suitHeavy" },
    score: "high",
  },
  {
    id: "suit-light",
    name: "Suit-Light",
    shortName: "Light",
    summary: "One suit is cut down to six cards before the deal.",
    detail: "Hearts are the current light suit, making heart flushes scarce while other suits remain complete.",
    tags: ["deck", "suits"],
    deal: { ...standardDeal, deck: "suitLight" },
    score: "high",
  },
  {
    id: "inverted-deck",
    name: "Inverted Deck",
    shortName: "Invert",
    summary: "Aces are low and twos rank above kings.",
    detail: "Showdown maps rank strength through an inverted order before comparing poker hands.",
    tags: ["deck", "ranks"],
    deal: standardDeal,
    rankTransform: "inverted",
    score: "high",
  },
  {
    id: "jokers-in",
    name: "Jokers In",
    shortName: "Jokers",
    summary: "Two jokers are added to the deck as wild cards.",
    detail: "Each joker can become the best possible card identity for the hand holding it at showdown.",
    tags: ["deck", "wild"],
    deal: { ...standardDeal, deck: "jokers" },
    wildCards: { metas: ["joker"] },
    score: "high",
  },
  {
    id: "wild-suit",
    name: "Wild Suit",
    shortName: "Wild S",
    summary: "One announced suit is wild for showdown.",
    detail: "Hearts are the current announced wild suit; every heart can substitute into a stronger identity at reveal.",
    tags: ["wild", "suits"],
    deal: standardDeal,
    wildCards: { suits: ["H"] },
    score: "high",
  },
  {
    id: "wild-rank",
    name: "Wild Rank",
    shortName: "Wild R",
    summary: "One announced rank is wild for showdown.",
    detail: "Sevens are the current wild rank and can substitute into stronger identities at reveal.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["7"] },
    score: "high",
  },
  {
    id: "wild-rank-roulette",
    name: "Wild Rank Roulette",
    shortName: "Roulette",
    summary: "The wild rank rotates during the hand.",
    detail: "The accelerated implementation uses sevens as the reveal-phase wild rank while the phase-display rotation layer is pending.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["7"] },
    score: "high",
  },
  {
    id: "wild-aces",
    name: "Wild Aces",
    shortName: "Wild A",
    summary: "Aces are wild for showdown.",
    detail: "Every ace can substitute into the strongest available identity at reveal.",
    tags: ["wild", "aces"],
    deal: standardDeal,
    wildCards: { ranks: ["A"] },
    score: "high",
  },
  {
    id: "wild-faces",
    name: "Wild Faces",
    shortName: "Faces",
    summary: "Jacks, queens, and kings are wild.",
    detail: "Face cards can substitute into stronger identities at reveal, creating volatile high-card and made-hand swings.",
    tags: ["wild", "faces"],
    deal: standardDeal,
    wildCards: { ranks: ["J", "Q", "K"] },
    score: "high",
  },
  {
    id: "anti-wild",
    name: "Anti-Wild",
    shortName: "Anti",
    summary: "One announced rank is banned from scoring.",
    detail: "Sevens are ignored by the showdown evaluator, shrinking hands and boards before hand comparison.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    excludedRanks: ["7"],
    score: "high",
  },
  {
    id: "cursed-card",
    name: "Cursed Card",
    shortName: "Cursed",
    summary: "One marked card downgrades the hand holding it.",
    detail: "The cursed ace of hearts is shuffled into the deck; any hand holding it is forced below uncursed hands at reveal.",
    tags: ["identity", "marked"],
    deal: { ...standardDeal, deck: "cursed" },
    forceRankByMeta: { last: "cursed" },
    score: "high",
  },
  {
    id: "blessed-card",
    name: "Blessed Card",
    shortName: "Blessed",
    summary: "One marked card upgrades the hand holding it.",
    detail: "The blessed ace of hearts is shuffled into the deck; any hand holding it is forced above unblessed hands at reveal.",
    tags: ["identity", "marked"],
    deal: { ...standardDeal, deck: "blessed" },
    forceRankByMeta: { first: "blessed" },
    score: "high",
  },
  {
    id: "counterfeit",
    name: "Counterfeit",
    shortName: "Counter",
    summary: "One face-down hole card per hand is value zero.",
    detail: "The first kept hole card in every hand is marked counterfeit and ignored by showdown scoring.",
    tags: ["identity", "holes"],
    deal: { ...standardDeal, counterfeitHoleCards: 1 },
    excludedMetas: ["counterfeit"],
    score: "high",
  },
  {
    id: "glitch-card",
    name: "Glitch Card",
    shortName: "Glitch",
    summary: "One card flickers and resolves at reveal.",
    detail: "The glitched ace of hearts resolves as a reveal-time wild card for the hand holding it.",
    tags: ["identity", "wild"],
    deal: { ...standardDeal, deck: "glitch" },
    wildCards: { metas: ["glitched"] },
    score: "high",
  },
  {
    id: "two-suited-card",
    name: "Two-Suited Card",
    shortName: "2-Suit",
    summary: "One marked card can satisfy multiple suit identities.",
    detail: "The two-suited ace of hearts is evaluated as a suit-flexible reveal card.",
    tags: ["identity", "suits"],
    deal: { ...standardDeal, deck: "twoSuited" },
    wildCards: { metas: ["twoSuited"] },
    score: "high",
  },
  {
    id: "wild-connector",
    name: "Wild Connector",
    shortName: "Connect",
    summary: "Adjacent ranks can behave like a pair.",
    detail: "A connected rank pair creates a synthetic pair during showdown evaluation.",
    tags: ["identity", "ranks"],
    deal: standardDeal,
    syntheticPair: "adjacent",
    score: "high",
  },
  {
    id: "wild-spread",
    name: "Wild Spread",
    shortName: "Spread",
    summary: "Far-apart ranks can behave like a pair.",
    detail: "A wide rank spread creates a synthetic pair during showdown evaluation.",
    tags: ["identity", "ranks"],
    deal: standardDeal,
    syntheticPair: "spread",
    score: "high",
  },
  {
    id: "marked-deck",
    name: "Marked Deck",
    shortName: "Marked",
    summary: "One card's deck position is known to all.",
    detail: "The marked ace of hearts carries metadata for display and audit without changing showdown strength.",
    tags: ["identity", "information"],
    deal: { ...standardDeal, deck: "marked" },
    score: "high",
  },
  {
    id: "trickster-card",
    name: "Trickster Card",
    shortName: "Trick",
    summary: "A designated card always counts as the hand's worst.",
    detail: "The trickster ace of hearts forces the hand holding it below non-trickster hands at reveal.",
    tags: ["identity", "marked"],
    deal: { ...standardDeal, deck: "trickster" },
    forceRankByMeta: { last: "trickster" },
    score: "high",
  },
  {
    id: "wild-edge",
    name: "Wild Edge",
    shortName: "Edge",
    summary: "Twos and aces are wild.",
    detail: "Both deck edges can substitute into the strongest available reveal identity.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["2", "A"] },
    score: "high",
  },
  {
    id: "twin-suits",
    name: "Twin Suits",
    shortName: "Twins",
    summary: "Hearts/diamonds and clubs/spades merge for flushes.",
    detail: "Red suits evaluate as one suit and black suits evaluate as one suit for showdown.",
    tags: ["identity", "suits"],
    deal: standardDeal,
    suitTransform: "color",
    score: "high",
  },
  {
    id: "card-counters",
    name: "Card Counters",
    shortName: "Counters",
    summary: "A public Deck chip shows the remaining-deck count.",
    detail: "In the verified eight-hand run, the felt showed `Deck 28 cards remain` from preflop through reveal while scoring used the normal five-card board.",
    tags: ["visibility", "info"],
    deal: standardDeal,
    infoFeatures: ["deck-count"],
    score: "high",
  },
  {
    id: "suit-census",
    name: "Suit Census",
    shortName: "Suit C",
    summary: "A public Suits chip shows the remaining-deck suit counts.",
    detail: "In the verified two-player run, the felt showed `Suits H7 D9 C13 S11` from preflop through reveal while scoring used the normal five-card board.",
    tags: ["visibility", "suits"],
    deal: standardDeal,
    infoFeatures: ["suit-census"],
    score: "high",
  },
  {
    id: "rank-census",
    name: "Rank Census",
    shortName: "Rank C",
    summary: "A public Ranks chip shows the remaining-deck rank counts.",
    detail: "In the verified two-player run, the felt showed `Ranks 43 K3 34 83 93 52 24 A3 64 73 T3 Q3 J2` from preflop through reveal while scoring used the normal five-card board.",
    tags: ["visibility", "ranks"],
    deal: standardDeal,
    infoFeatures: ["rank-census"],
    score: "high",
  },
  {
    id: "burn-reveal",
    name: "Burn Reveal",
    shortName: "Burn",
    summary: "A public Burn chip shows the three burned cards.",
    detail: "In the verified two-player run, the felt showed `Burn 5D JS 7S` from preflop through reveal while scoring used the normal five-card board.",
    tags: ["visibility", "burn"],
    deal: standardDeal,
    infoFeatures: ["burn-reveal"],
    score: "high",
  },
  {
    id: "hint-card",
    name: "Hint Card",
    shortName: "Hint",
    summary: "A public Hint chip appears only on the turn.",
    detail: "In the verified two-player run, no chip appeared preflop or flop, the turn showed `Hint 5C`, and river/reveal returned to the normal five-card board without the hint.",
    tags: ["visibility", "deck"],
    deal: standardDeal,
    infoFeatures: ["hint-card"],
    score: "high",
  },
  {
    id: "decoy",
    name: "Decoy",
    shortName: "Decoy",
    summary: "A public Decoy chip warns that a table card does not score; the chip does not name or mark which card.",
    detail: "The felt shows the generic `One table card is a decoy and does not score` chip through reveal and the scoring board still uses the normal five cards; the specific decoy is not surfaced to players.",
    tags: ["visibility", "decoy"],
    deal: standardDeal,
    infoFeatures: ["decoy"],
    score: "high",
  },
  {
    id: "lying-mirror",
    name: "Lying Mirror",
    shortName: "Mirror",
    summary: "A public Mirror chip shows a fake flop only on flop.",
    detail: "In the verified two-player run, no chip appeared preflop, flop showed `Mirror Fake flop: 7H AC 6C`, and turn/river/reveal scored against the normal five-card board.",
    tags: ["visibility", "fake"],
    deal: standardDeal,
    infoFeatures: ["lying-mirror"],
    score: "high",
  },
  {
    id: "whisper-chain",
    name: "Whisper Chain",
    shortName: "Whisper",
    summary: "Each player receives a private Whisper chip about a neighbor.",
    detail: "In the verified two-human run, Alpha saw `Whisper Beta: ...` while Beta saw `Whisper Alpha: ...`; each recipient saw only their own private chip.",
    tags: ["visibility", "holes"],
    deal: { ...standardDeal, visibleHoleCards: { preflop: 1, flop: 1, turn: 1, river: 1, reveal: 2 } },
    infoFeatures: ["whisper-chain"],
    score: "high",
  },
  {
    id: "periscope",
    name: "Periscope",
    shortName: "Scope",
    summary: "At river, each player receives a private Periscope chip.",
    detail: "In the verified two-human run, Alpha saw `Periscope Beta: 8D` while Beta saw `Periscope Alpha: 9D`; each chip stayed private to its recipient.",
    tags: ["visibility", "river"],
    deal: { ...standardDeal, visibleHoleCards: { river: 1, reveal: 2 } },
    infoFeatures: ["periscope"],
    score: "high",
  },
  {
    id: "spotlight-rotation",
    name: "Spotlight Rotation",
    shortName: "Spotlight",
    summary: "A rotating hand is fully spotlighted each phase.",
    detail: "The accelerated pass exposes spotlight mode info and full public holes across streets.",
    tags: ["visibility", "holes"],
    deal: { ...standardDeal, visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 } },
    infoFeatures: ["spotlight"],
    score: "high",
  },
  {
    id: "half-lit-holes",
    name: "Half-Lit Holes",
    shortName: "Half-Lit",
    summary: "Each hand alternates which hole card is visible.",
    detail: "One hole card is public at every street, alternating between first and second before both are revealed.",
    tags: ["visibility", "holes"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 1, flop: 1, turn: 1, river: 1, reveal: 2 },
      visibleHoleCardIndexes: { preflop: [0], flop: [1], turn: [0], river: [1], reveal: [0, 1] },
    },
    infoFeatures: ["half-lit-holes"],
    score: "high",
  },
  {
    id: "mirror-hole",
    name: "Mirror Hole",
    shortName: "Mirror H",
    summary: "Each player receives a private Mirror chip for a neighbor hand.",
    detail: "In the verified two-human run, Alpha saw `Mirror Beta: 6C` while Beta saw `Mirror Alpha: KH`; both chips stayed private through reveal.",
    tags: ["visibility", "neighbor"],
    deal: standardDeal,
    infoFeatures: ["mirror-hole"],
    score: "high",
  },
  {
    id: "group-mind",
    name: "Group Mind",
    shortName: "Group",
    summary: "Everyone sees one shared hole card from every hand.",
    detail: "One public hole-card anchor per hand rotates as shared table knowledge across phases.",
    tags: ["visibility", "holes"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 1, flop: 1, turn: 1, river: 1, reveal: 2 },
      visibleHoleCardIndexes: { preflop: [0], flop: [1], turn: [0], river: [1], reveal: [0, 1] },
    },
    infoFeatures: ["group-mind"],
    score: "high",
  },
  {
    id: "tag-team",
    name: "Tag Team",
    shortName: "Tag",
    summary: "Each player receives a private Tag chip with a neighbor's full hole cards.",
    detail: "In the verified two-human run, Alpha saw `Tag Beta: 2D 9D` while Beta saw `Tag Alpha: 4S KH`; both private chips persisted from preflop through reveal.",
    tags: ["visibility", "holes"],
    deal: { ...standardDeal, visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 } },
    infoFeatures: ["tag-team"],
    score: "high",
  },
  {
    id: "smoke-hole",
    name: "Smoke Hole",
    shortName: "Smoke",
    summary: "Hole cards are suit-only until turn.",
    detail: "Every hand exposes only suit hints through flop, then full visible hole cards from turn onward.",
    tags: ["visibility", "suits"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 },
      visibleHoleCardDetail: { preflop: "suit", flop: "suit", turn: "full", river: "full", reveal: "full" },
    },
    infoFeatures: ["smoke-hole"],
    score: "high",
  },
  {
    id: "heat-map",
    name: "Heat Map",
    shortName: "Heat",
    summary: "The table is told whether the deck skews high or low.",
    detail: "A public mode info payload compares high and low ranks left in the deck.",
    tags: ["visibility", "deck"],
    deal: standardDeal,
    infoFeatures: ["heat-map"],
    score: "high",
  },
  {
    id: "suit-heat",
    name: "Suit Heat",
    shortName: "Suit Heat",
    summary: "The table is told which suit is over-represented.",
    detail: "A public mode info payload names the most common remaining deck suit.",
    tags: ["visibility", "suits"],
    deal: standardDeal,
    infoFeatures: ["suit-heat"],
    score: "high",
  },
  {
    id: "sample-draw",
    name: "Sample Draw",
    shortName: "Sample",
    summary: "The river shows a public Sample chip with three off-board cards.",
    detail: "In the verified run, no Sample chip appeared before river; river showed `Sample TD 3D 8S`, then reveal and scoring used the normal five-card board.",
    tags: ["visibility", "deck"],
    deal: standardDeal,
    infoFeatures: ["sample-draw"],
    score: "high",
  },
  {
    id: "past-trace",
    name: "Past Trace",
    shortName: "Trace",
    summary: "The table tracks previous-hand memory.",
    detail: "The first playable pass exposes trace status; future multi-round memory can fill in prior holes.",
    tags: ["visibility", "memory"],
    deal: standardDeal,
    infoFeatures: ["past-trace"],
    score: "high",
  },
  {
    id: "tell",
    name: "Tell",
    shortName: "Tell",
    summary: "A public Tell chip names one true board fact.",
    detail: "In the verified run, the chip showed `Tell Board card 1 is 2S` from preflop through reveal, and the first board card was 2S.",
    tags: ["visibility", "truth"],
    deal: standardDeal,
    infoFeatures: ["tell"],
    score: "high",
  },
  {
    id: "communal-glance",
    name: "Communal Glance",
    shortName: "Glance",
    summary: "The table sees one random hole-card slot.",
    detail: "One shared hole-card anchor per hand is public for the hand, preserving symmetric information.",
    tags: ["visibility", "holes"],
    deal: { ...standardDeal, visibleHoleCards: { preflop: 1, flop: 1, turn: 1, river: 1, reveal: 2 } },
    infoFeatures: ["communal-glance"],
    score: "high",
  },
  {
    id: "suit-whisper",
    name: "Suit Whisper",
    shortName: "S-Whisper",
    summary: "A public Suit Whisper chip names one hand id and an absent suit.",
    detail: "In the verified run, `Suit Whisper 4967414e-d15c-4669-a575-215546e7fb7f-0 does not hold C` stayed visible from preflop through reveal.",
    tags: ["visibility", "suits"],
    deal: standardDeal,
    infoFeatures: ["suit-whisper"],
    score: "high",
  },
  {
    id: "rank-whisper",
    name: "Rank Whisper",
    shortName: "R-Whisper",
    summary: "A public Rank Whisper chip names one hand id and an absent rank.",
    detail: "In the verified run, `Rank Whisper 4173ee16-aed8-4c5e-94b1-117a79209c57-0 does not hold 2` stayed visible from preflop through reveal.",
    tags: ["visibility", "ranks"],
    deal: standardDeal,
    infoFeatures: ["rank-whisper"],
    score: "high",
  },
  {
    id: "phantom-card",
    name: "Phantom Card",
    shortName: "Phantom",
    summary: "A public Phantom chip names a rank absent from at least one hand.",
    detail: "In the verified run, `Phantom 5 is not in at least one hand` stayed visible from preflop through reveal.",
    tags: ["visibility", "ranks"],
    deal: standardDeal,
    infoFeatures: ["phantom-card"],
    score: "high",
  },
  {
    id: "late-hand-reveal",
    name: "Late Hand Reveal",
    shortName: "Late Hand",
    summary: "The river shows a public Reveal chip and turns hole cards face up.",
    detail: "In the verified run, no Reveal chip appeared before river; river showed `Reveal All hole cards are now public` and exposed the bot hand before normal reveal scoring.",
    tags: ["visibility", "river"],
    deal: { ...standardDeal, visibleHoleCards: { river: 2, reveal: 2 } },
    infoFeatures: ["late-hand-reveal"],
    score: "high",
  },
  {
    id: "earthquake",
    name: "Earthquake",
    shortName: "Quake",
    summary: "A public Earthquake chip appears each phase and the board order changes at turn.",
    detail: "In the verified run, flop `2H JH TD` became turn `JH TD KC 7H`, then river `JH TD KC 7H 2H`, with `Earthquake Earthquake is active on <phase>` visible through reveal.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { turn: ["shuffleCommunity"] },
    infoFeatures: ["earthquake"],
    score: "high",
  },
  {
    id: "tornado",
    name: "Tornado",
    shortName: "Tornado",
    summary: "A public Tornado chip appears each phase and hole cards rotate at turn.",
    detail: "In the verified run, Alpha's hand changed from `2S 3H` to `8S 9S` at turn, Sage revealed the original `2S 3H`, and `Tornado Tornado is active on <phase>` stayed visible through reveal.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateHoleCardsClockwise"] },
    infoFeatures: ["tornado"],
    score: "high",
  },
  {
    id: "lightning",
    name: "Lightning",
    shortName: "Lightning",
    summary: "A public Lightning chip appears each phase and first hole cards jump one rank at river.",
    detail: "In the verified run, Alpha's hand changed from `QC TC` to `KC TC` at river, and `Lightning Lightning is active on <phase>` stayed visible through reveal.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["incrementFirstHolePerHand"] },
    infoFeatures: ["lightning"],
    score: "high",
  },
  {
    id: "flood",
    name: "Flood",
    shortName: "Flood",
    summary: "A public Flood chip appears each phase and ranks 2-5 score as wild cards.",
    detail: "In the verified run, `Flood Flood is active on <phase>` stayed visible through reveal; Sly scored `Wild: Straight, A High` and Alpha's `4S QH` scored `Wild: Three of a Kind, Q's`.",
    tags: ["event", "wild"],
    deal: standardDeal,
    wildCards: { ranks: ["2", "3", "4", "5"] },
    infoFeatures: ["flood"],
    score: "high",
  },
  {
    id: "drought",
    name: "Drought",
    shortName: "Drought",
    summary: "A public Drought chip appears each phase and face cards leave the board at turn.",
    detail: "In the verified two-human run, flop `QD 9C QS` became turn/reveal `9C 6S 8S`, and `Drought Drought is active on <phase>` stayed visible through reveal.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["removeFaceCards"] },
    infoFeatures: ["drought"],
    score: "high",
  },
  {
    id: "plague",
    name: "Plague",
    shortName: "Plague",
    summary: "A public Plague chip appears each phase and sevens are removed at turn when present.",
    detail: "In the verified run, `Plague Plague is active on <phase>` stayed visible through reveal; no sevens were visible before turn, and the board finished `9S 6D 8C 3D 8H` with normal scoring.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["removeSevens"] },
    infoFeatures: ["plague"],
    score: "high",
  },
  {
    id: "solar-flare",
    name: "Solar Flare",
    shortName: "Flare",
    summary: "A public Solar Flare chip appears each phase and suits rotate at turn.",
    detail: "In the verified run, flop `8C AC 4D` became turn `8S AS 4C JH`, Alpha's hand changed from `2D 6H` to `2C 6D`, and `Solar Flare Solar Flare is active on <phase>` stayed visible through reveal.",
    tags: ["event", "suits"],
    deal: standardDeal,
    phaseEffects: { turn: ["reassignAllSuits"] },
    infoFeatures: ["solar-flare"],
    score: "high",
  },
  {
    id: "meteor",
    name: "Meteor",
    shortName: "Meteor",
    summary: "A public Meteor chip appears each phase and one community card is replaced at turn.",
    detail: "In the verified run, flop `QH 5C 4S` became turn `QH 5H 4S 8H`, with `Meteor Meteor is active on <phase>` visible through reveal.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { turn: ["randomReplaceVisibleCommunity"] },
    infoFeatures: ["meteor"],
    score: "high",
  },
  {
    id: "mirror-universe",
    name: "Mirror Universe",
    shortName: "Mirror U",
    summary: "A public Mirror Universe chip appears each phase and ranks invert at river.",
    detail: "In the verified run, Alpha's `9H QC` became `7H 4C`, the turn board `KH 4C 9S AD` became river `3H QC 7S 2D AH`, and `Mirror Universe Mirror Universe is active on <phase>` stayed visible through reveal.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["invertAllRanks"] },
    infoFeatures: ["mirror-universe"],
    score: "high",
  },
  {
    id: "wildfire",
    name: "Wildfire",
    shortName: "Wildfire",
    summary: "A public Wildfire chip appears each phase and ranks adjacent to the river burn away.",
    detail: "In the verified run, river `6C` burned adjacent ranks `5` and `7`, so Alpha's `KC 5D` became `KC`, Doc revealed only `AS`, and `Wildfire Wildfire is active on <phase>` stayed visible through reveal.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["removeAdjacentToRiver"] },
    infoFeatures: ["wildfire"],
    score: "high",
  },
  {
    id: "avalanche",
    name: "Avalanche",
    shortName: "Avalanche",
    summary: "A public Avalanche chip appears each phase and the board reveals 3/5/7 cards.",
    detail: "In the verified run, the board grew from `4D 8S 4S` to `4D 8S 4S AD 5C` to `4D 8S 4S AD 5C TD 2S`, with `Avalanche Avalanche is active on <phase>` visible through reveal.",
    tags: ["event", "board"],
    deal: { ...standardDeal, communityCards: 7, visibleCommunityCards: { flop: 3, turn: 5, river: 7, reveal: 7 } },
    infoFeatures: ["avalanche"],
    score: "high",
  },
  {
    id: "storm-surge",
    name: "Storm Surge",
    shortName: "Surge",
    summary: "A public Storm Surge chip appears each phase and older board cards are swept away.",
    detail: "In the verified run, flop `2C 7C TS` became turn `7C TS 3D` and river `TS 3D`, with `Storm Surge Storm Surge is active on <phase>` visible through reveal.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { flop: ["stormSurge"], turn: ["stormSurge"], river: ["stormSurge"] },
    infoFeatures: ["storm-surge"],
    score: "high",
  },
  {
    id: "static",
    name: "Static",
    shortName: "Static",
    summary: "A public Static chip appears each phase and board suits scramble while ranks stay fixed.",
    detail: "In the verified run, board ranks stayed `5 A 7` while suits changed from flop `5C AH 7C` to turn `5S AD 7S 2S` to river `5H AC 7H 2H QD`, with `Static Static is active on <phase>` visible through reveal.",
    tags: ["event", "suits"],
    deal: standardDeal,
    phaseEffects: { flop: ["scrambleCommunitySuits"], turn: ["scrambleCommunitySuits"], river: ["scrambleCommunitySuits"] },
    infoFeatures: ["static"],
    score: "high",
  },
  {
    id: "wormhole",
    name: "Wormhole",
    shortName: "Wormhole",
    summary: "A public Wormhole chip appears each phase and the first two hands swap first hole cards at river.",
    detail: "In the verified run, Alpha's `TS AD` became `9S AD` at river while the board was `JH KS 4S 9C QS`, and `Wormhole Wormhole is active on <phase>` stayed visible through reveal.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { river: ["swapFirstCardsFirstTwoHands"] },
    infoFeatures: ["wormhole"],
    score: "high",
  },
  {
    id: "black-hole",
    name: "Black Hole",
    shortName: "Black Hole",
    summary: "A public Black Hole chip appears each phase and the river removes the last community card.",
    detail: "In the verified run, the board reached turn as `8H 8D 9C QS`, stayed four cards at river/reveal after `Remove Last Community fired`, and `Black Hole Black Hole is active on <phase>` stayed visible through reveal.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { river: ["removeLastCommunity"] },
    infoFeatures: ["black-hole"],
    score: "high",
  },
  {
    id: "gravity-well",
    name: "Gravity Well",
    shortName: "Gravity",
    summary: "A public Gravity Well chip appears each phase and each hand's highest hole card upgrades at river.",
    detail: "In the verified run, Alpha's `KH 6C` became `AH 6C` at river on board `AC 9D JH JC 5S`, with `Gravity Well Gravity Well is active on <phase>` visible through reveal.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["upgradeHighestHole"] },
    infoFeatures: ["gravity-well"],
    score: "high",
  },
  {
    id: "heat-wave",
    name: "Heat Wave",
    shortName: "Heat W",
    summary: "At turn, all face cards become aces.",
    detail: "Jacks, queens, and kings in hands and board convert to aces when turn begins.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["faceCardsToAces"] },
    infoFeatures: ["heat-wave"],
    score: "high",
  },
  {
    id: "cold-snap",
    name: "Cold Snap",
    shortName: "Cold",
    summary: "At turn, all face cards become twos.",
    detail: "Jacks, queens, and kings in hands and board convert to twos when turn begins.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["faceCardsToTwos"] },
    infoFeatures: ["cold-snap"],
    score: "high",
  },
  {
    id: "fog-bank",
    name: "Fog Bank",
    shortName: "Fog",
    summary: "Community cards show only color until reveal.",
    detail: "The board is color-only from flop through river, then clears at reveal.",
    tags: ["event", "visibility"],
    deal: { ...standardDeal, visibleCommunityCardDetail: { flop: "color", turn: "color", river: "color" } },
    infoFeatures: ["fog-bank"],
    score: "high",
  },
  {
    id: "rainstorm",
    name: "Rainstorm",
    shortName: "Rain",
    summary: "Every phase, one community card is replaced.",
    detail: "A fresh deck card replaces one visible community card at flop, turn, and river.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { flop: ["randomReplaceVisibleCommunity"], turn: ["randomReplaceVisibleCommunity"], river: ["randomReplaceVisibleCommunity"] },
    infoFeatures: ["rainstorm"],
    score: "high",
  },
  {
    id: "aurora",
    name: "Aurora",
    shortName: "Aurora",
    summary: "At river, suits swap within color pairs.",
    detail: "The same deterministic suit reassignment used by the flare hits at river.",
    tags: ["event", "suits"],
    deal: standardDeal,
    phaseEffects: { river: ["reassignAllSuits"] },
    infoFeatures: ["aurora"],
    score: "high",
  },
  {
    id: "hurricane",
    name: "Hurricane",
    shortName: "Hurricane",
    summary: "At river, every player loses one hole card.",
    detail: "Each hand loses its final hole card when river begins.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { river: ["removeOneHolePerHand"] },
    infoFeatures: ["hurricane"],
    score: "high",
  },
  {
    id: "ice-age",
    name: "Ice Age",
    shortName: "Ice",
    summary: "Even ranks are frozen out of scoring.",
    detail: "Even-ranked cards are skipped by the reveal evaluator.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    excludedRanks: ["2", "4", "6", "8", "T", "Q"],
    infoFeatures: ["ice-age"],
    score: "high",
  },
  {
    id: "volcano",
    name: "Volcano",
    shortName: "Volcano",
    summary: "At river, one face-up card from each hand is destroyed.",
    detail: "The first hole card in each hand is destroyed when river begins.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { river: ["removeFirstHolePerHand"] },
    infoFeatures: ["volcano"],
    score: "high",
  },
  {
    id: "quantum-shuffle",
    name: "Quantum Shuffle",
    shortName: "Quantum",
    summary: "At turn, all hole cards are redistributed.",
    detail: "Hole cards are gathered, rotated, and redealt across the table when turn begins.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["shuffleAllHoleCards"] },
    infoFeatures: ["quantum-shuffle"],
    score: "high",
  },
  {
    id: "schrodingers-hole",
    name: "Schrodinger's Hole",
    shortName: "Schrodinger",
    summary: "Hole cards render uncertain until reveal collapses them.",
    detail: "In the verified run, private cards displayed as uncertain `?` cards before reveal, then flipped into concrete ranks and suits for final high-hand scoring.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "holes" },
    identityResolution: "bestPossible",
    infoFeatures: ["schrodingers-hole"],
    score: "high",
  },
  {
    id: "quantum-flop",
    name: "Quantum Flop",
    shortName: "Q Flop",
    summary: "Three possible flops exist at once.",
    detail: "Nine community cards form three flop boards; each hand scores against its best quantum board.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      communityCards: 9,
      boardLayout: {
        kind: "grid",
        slots: [
          { row: 0, col: 0, group: "flop-a" },
          { row: 0, col: 1, group: "flop-a" },
          { row: 0, col: 2, group: "flop-a" },
          { row: 1, col: 0, group: "flop-b" },
          { row: 1, col: 1, group: "flop-b" },
          { row: 1, col: 2, group: "flop-b" },
          { row: 2, col: 0, group: "flop-c" },
          { row: 2, col: 1, group: "flop-c" },
          { row: 2, col: 2, group: "flop-c" },
        ],
      },
      visibleCommunityCards: { flop: 9, turn: 9, river: 9, reveal: 9 },
      boards: { count: 3, cardsPerBoard: 3, scoring: "best" },
    },
    infoFeatures: ["quantum-flop"],
    score: "high",
  },
  {
    id: "probability-cloud",
    name: "Probability Cloud",
    shortName: "Cloud",
    summary: "Community cards carry unresolved alternate ranks.",
    detail: "Board cards have alternate identities before reveal; scoring resolves to the strongest possible version.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "board" },
    identityResolution: "bestPossible",
    infoFeatures: ["probability-cloud"],
    score: "high",
  },
  {
    id: "holographic-card",
    name: "Holographic Card",
    shortName: "Holo",
    summary: "Every community card carries multiple possible identities until reveal.",
    detail: "All flop/turn/river community cards render as uncertain (yellow ring + ?), then collapse at reveal to a single identity used for scoring.",
    tags: ["insanity", "visibility"],
    deal: { ...standardDeal, possibleIdentities: "board" },
    identityResolution: "bestPossible",
    infoFeatures: ["holographic-card"],
    score: "high",
  },
  {
    id: "schrodingers-board",
    name: "Schrodinger's Board",
    shortName: "S Board",
    summary: "The board exists in two possible versions.",
    detail: "Every community card carries a second possible identity; reveal scoring picks the strongest coherent version per hand.",
    tags: ["insanity", "board"],
    deal: { ...standardDeal, possibleIdentities: "board" },
    identityResolution: "bestPossible",
    infoFeatures: ["schrodingers-board"],
    score: "high",
  },
  {
    id: "card-multiverse",
    name: "Card Multiverse",
    shortName: "Multiverse",
    summary: "The board declares a 4x5 multiverse grid; ranking-claim does not enable Ready in current builds, so the hand stays stuck at preflop.",
    detail: "Catalogued as a four-row twenty-card grid, but the standard ranking controls cannot advance the hand past preflop pending a board-slot-aware claim flow.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      communityCards: 20,
      boardLayout: {
        kind: "grid",
        slots: [
          { row: 0, col: 0, group: "universe-a" },
          { row: 0, col: 1, group: "universe-a" },
          { row: 0, col: 2, group: "universe-a" },
          { row: 0, col: 3, group: "universe-a" },
          { row: 0, col: 4, group: "universe-a" },
          { row: 1, col: 0, group: "universe-b" },
          { row: 1, col: 1, group: "universe-b" },
          { row: 1, col: 2, group: "universe-b" },
          { row: 1, col: 3, group: "universe-b" },
          { row: 1, col: 4, group: "universe-b" },
          { row: 2, col: 0, group: "universe-c" },
          { row: 2, col: 1, group: "universe-c" },
          { row: 2, col: 2, group: "universe-c" },
          { row: 2, col: 3, group: "universe-c" },
          { row: 2, col: 4, group: "universe-c" },
          { row: 3, col: 0, group: "universe-d" },
          { row: 3, col: 1, group: "universe-d" },
          { row: 3, col: 2, group: "universe-d" },
          { row: 3, col: 3, group: "universe-d" },
          { row: 3, col: 4, group: "universe-d" },
        ],
      },
      visibleCommunityCards: { flop: 5, turn: 10, river: 20, reveal: 20 },
      boards: { count: 4, cardsPerBoard: 5, scoring: "best" },
    },
    infoFeatures: ["card-multiverse"],
    score: "high",
  },
  {
    id: "reality-tear",
    name: "Reality Tear",
    shortName: "Tear",
    summary: "One reality-torn card has multiple possible identities.",
    detail: "Cards can carry alternate identities and reveal scoring resolves the strongest possible version.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "holesAndBoard" },
    identityResolution: "bestPossible",
    infoFeatures: ["reality-tear"],
    score: "high",
  },
  {
    id: "identity-crisis",
    name: "Identity Crisis",
    shortName: "Crisis",
    summary: "At turn, a hole card and board card swap identities.",
    detail: "The first hand's first hole card swaps with the first community card when turn begins.",
    tags: ["insanity", "identity"],
    deal: standardDeal,
    phaseEffects: { turn: ["swapFirstHoleWithFirstCommunity"] },
    infoFeatures: ["identity-crisis"],
    score: "high",
  },
  {
    id: "drunken-display",
    name: "Drunken Display",
    shortName: "Drunken",
    summary: "Displayed ranks wobble away from truth.",
    detail: "The accelerated pass represents rank wobble as unresolved possible identities while reveal scoring keeps the strongest truth.",
    tags: ["insanity", "visibility"],
    deal: { ...standardDeal, possibleIdentities: "holesAndBoard" },
    identityResolution: "bestPossible",
    infoFeatures: ["drunken-display"],
    score: "high",
  },
  {
    id: "photographic-negative",
    name: "Photographic Negative",
    shortName: "Negative",
    summary: "Card colors invert visually after turn.",
    detail: "The board is color-only from turn through river, forcing players to reason through the negative display.",
    tags: ["insanity", "visibility"],
    deal: { ...standardDeal, visibleCommunityCardDetail: { turn: "color", river: "color" } },
    infoFeatures: ["photographic-negative"],
    score: "high",
  },
  {
    id: "synesthesia",
    name: "Synesthesia",
    shortName: "Synesthesia",
    summary: "Cards are seen through rotating sensory filters.",
    detail: "The accelerated cooperative pass exposes rank-only community cards at flop, suit-only at turn, and color-only at river.",
    tags: ["insanity", "visibility"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetail: { flop: "rank", turn: "suit", river: "color" },
    },
    infoFeatures: ["synesthesia"],
    score: "high",
  },
  {
    id: "shapeshifter",
    name: "Shapeshifter",
    shortName: "Shifter",
    summary: "One community card changes identity each street.",
    detail: "The first community card upgrades one rank at flop, turn, and river.",
    tags: ["insanity", "identity"],
    deal: standardDeal,
    phaseEffects: { flop: ["incrementFirstCommunityRank"], turn: ["incrementFirstCommunityRank"], river: ["incrementFirstCommunityRank"] },
    infoFeatures: ["shapeshifter"],
    score: "high",
  },
  {
    id: "card-rebellion",
    name: "Card Rebellion",
    shortName: "Rebellion",
    summary: "At turn, hands rebel and rotate around the table.",
    detail: "Hand contents rotate one seat at turn, representing cards moving toward their closest match.",
    tags: ["insanity", "hands"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateHoleCardsClockwise"] },
    infoFeatures: ["card-rebellion"],
    score: "high",
  },
  {
    id: "card-theatre",
    name: "Card Theatre",
    shortName: "Theatre",
    summary: "A rotating hand is described instead of plainly shown.",
    detail: "The accelerated pass publishes theatre clues through mode info while preserving the normal ranking loop.",
    tags: ["insanity", "visibility"],
    deal: standardDeal,
    infoFeatures: ["card-theatre"],
    score: "high",
  },
  {
    id: "card-whisper-network",
    name: "Card Whisper Network",
    shortName: "Network",
    summary: "The Network mode shows a public Tell chip with one true board fact.",
    detail: "In the verified run, `Tell Board card 1 is 4C` appeared from preflop through reveal, and the first board card was 4C.",
    tags: ["insanity", "info"],
    deal: standardDeal,
    infoFeatures: ["card-whisper-network"],
    score: "high",
  },
  {
    id: "card-conscience",
    name: "Card Conscience",
    shortName: "Conscience",
    summary: "The deck announces a rank that has gone unused.",
    detail: "A public conscience payload names the first rank missing from hands and board.",
    tags: ["insanity", "info"],
    deal: standardDeal,
    infoFeatures: ["card-conscience"],
    score: "high",
  },
  {
    id: "card-festival",
    name: "Card Festival",
    shortName: "Festival",
    summary: "At river, one community card celebrates by boosting high.",
    detail: "The first community card becomes an ace at river as the playable rank-multiplier representation.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["festivalBoostFirstCommunity"] },
    infoFeatures: ["card-festival"],
    score: "high",
  },
  {
    id: "card-marriage",
    name: "Card Marriage",
    shortName: "Marriage",
    summary: "Cards are bonded into pairs.",
    detail: "A public mode info payload marks bonded-card behavior; movement remains symmetric in this pass.",
    tags: ["insanity", "identity"],
    deal: standardDeal,
    infoFeatures: ["card-marriage"],
    score: "high",
  },
  {
    id: "anti-memory",
    name: "Anti-Memory",
    shortName: "Anti-Memory",
    summary: "Seen cards fade while unseen cards surface.",
    detail: "The board starts fully visible, then progressively hides through river before reveal restores truth.",
    tags: ["insanity", "memory"],
    deal: { ...standardDeal, visibleCommunityCards: { preflop: 5, flop: 2, turn: 1, river: 0, reveal: 5 } },
    infoFeatures: ["anti-memory"],
    score: "high",
  },
  {
    id: "photographic-memory",
    name: "Photographic Memory",
    shortName: "Photo Mem",
    summary: "The flop disappears after you see it.",
    detail: "Flop is visible, then the board goes dark at turn and only partial river information returns.",
    tags: ["insanity", "memory"],
    deal: { ...standardDeal, visibleCommunityCards: { flop: 3, turn: 0, river: 2, reveal: 5 } },
    infoFeatures: ["photographic-memory"],
    score: "high",
  },
  {
    id: "memory-hole",
    name: "Memory Hole",
    shortName: "Mem Hole",
    summary: "At turn, one community card is forgotten.",
    detail: "One visible community card is replaced at turn and then masked through river.",
    tags: ["insanity", "memory"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetails: { turn: { 0: "hidden" }, river: { 0: "hidden" } },
    },
    phaseEffects: { turn: ["randomReplaceVisibleCommunity"] },
    infoFeatures: ["memory-hole"],
    score: "high",
  },
  {
    id: "time-echo",
    name: "Time Echo",
    shortName: "Echo",
    summary: "At river, the board returns to the flop.",
    detail: "The river phase truncates the board back to its first three community cards.",
    tags: ["insanity", "time"],
    deal: standardDeal,
    phaseEffects: { river: ["revertBoardToFlop"] },
    infoFeatures: ["time-echo"],
    score: "high",
  },
  {
    id: "reality-skip",
    name: "Reality Skip",
    shortName: "Skip",
    summary: "At turn, the timeline skips forward and snaps back.",
    detail: "The accelerated pass records the skip as public mode info with no lasting mutation.",
    tags: ["insanity", "time"],
    deal: standardDeal,
    infoFeatures: ["reality-skip"],
    score: "high",
  },
  {
    id: "reverse-universe",
    name: "Reverse Universe",
    shortName: "Reverse U",
    summary: "At river, table order and board order reverse.",
    detail: "The board and player order reverse when river begins while hand identities remain rankable.",
    tags: ["insanity", "time"],
    deal: standardDeal,
    phaseEffects: { river: ["reverseTableAndBoard"] },
    infoFeatures: ["reverse-universe"],
    score: "high",
  },
  {
    id: "card-singularity",
    name: "Card Singularity",
    shortName: "Singularity",
    summary: "At turn, each hand's cards collapse together.",
    detail: "The first two hole cards in each hand merge into one averaged-rank card when turn begins.",
    tags: ["insanity", "merge"],
    deal: standardDeal,
    phaseEffects: { turn: ["singularityAverageFirstTwoHoles"] },
    infoFeatures: ["card-singularity"],
    score: "high",
  },
  {
    id: "glitch-wars",
    name: "Glitch Wars",
    shortName: "Glitch Wars",
    summary: "At turn, board cards fight over suit identity.",
    detail: "The first community card absorbs the second community card's suit when turn begins.",
    tags: ["insanity", "suits"],
    deal: standardDeal,
    phaseEffects: { turn: ["firstCommunityAbsorbsSecondSuit"] },
    infoFeatures: ["glitch-wars"],
    score: "high",
  },
  {
    id: "card-convergence",
    name: "Card Convergence",
    shortName: "Converge",
    summary: "At river, one rank converges into aces.",
    detail: "Sevens become aces across hands and board as the playable convergence representation.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["convergeSevensToAces"] },
    infoFeatures: ["card-convergence"],
    score: "high",
  },
  {
    id: "card-halo",
    name: "Card Halo",
    shortName: "Halo",
    summary: "Neighboring ranks gain a pair aura.",
    detail: "Adjacent ranks can create a synthetic pair during showdown.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    syntheticPair: "adjacent",
    infoFeatures: ["card-halo"],
    score: "high",
  },
  {
    id: "card-vortex",
    name: "Card Vortex",
    shortName: "Vortex",
    summary: "At turn, ranks rotate around the table.",
    detail: "Hole-card ranks rotate across table order while suits stay in their slots.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateHoleRanksAcrossHands"] },
    infoFeatures: ["card-vortex"],
    score: "high",
  },
  {
    id: "card-eclipse-total",
    name: "Card Eclipse Total",
    shortName: "Eclipse T",
    summary: "At river, the highest rank in play vanishes.",
    detail: "Every card of the current highest rank is removed from hands and board at river.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["removeHighestRankInPlay"] },
    infoFeatures: ["card-eclipse-total"],
    score: "high",
  },
  {
    id: "card-plague-spread",
    name: "Card Plague Spread",
    shortName: "Spread",
    summary: "A plague rank infects more cards each phase.",
    detail: "One additional card converts to seven at flop, turn, and river.",
    tags: ["insanity", "spread"],
    deal: standardDeal,
    phaseEffects: { flop: ["spreadPlagueToFirstCard"], turn: ["spreadPlagueToFirstCard"], river: ["spreadPlagueToFirstCard"] },
    infoFeatures: ["card-plague-spread"],
    score: "high",
  },
  {
    id: "card-diaspora",
    name: "Card Diaspora",
    shortName: "Diaspora",
    summary: "At turn, every hand gives one card away.",
    detail: "The first hole card in each hand rotates to the next hand when turn begins.",
    tags: ["insanity", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateFirstHoleCardsClockwise"] },
    infoFeatures: ["card-diaspora"],
    score: "high",
  },
  {
    id: "card-soup",
    name: "Card Soup",
    shortName: "Soup",
    summary: "At turn, holes and burn pile mix together.",
    detail: "Hole cards are mixed with burn cards and redealt deterministically at turn.",
    tags: ["insanity", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["mixHolesWithBurn"] },
    infoFeatures: ["card-soup"],
    score: "high",
  },
  {
    id: "card-madness",
    name: "Card Madness",
    shortName: "Madness",
    summary: "At turn, every card swaps places.",
    detail: "All hole and community cards rotate one position through a single shared stream.",
    tags: ["insanity", "chaos"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateAllCardPositions"] },
    infoFeatures: ["card-madness"],
    score: "high",
  },
  {
    id: "card-tide",
    name: "Card Tide",
    shortName: "Tide",
    summary: "Every street, all ranks drift upward.",
    detail: "All ranks shift +1 at flop, turn, and river.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { flop: ["incrementAllRanks"], turn: ["incrementAllRanks"], river: ["incrementAllRanks"] },
    infoFeatures: ["card-tide"],
    score: "high",
  },
  {
    id: "card-drift",
    name: "Card Drift",
    shortName: "Drift",
    summary: "Every street, private cards drift upward.",
    detail: "Hole-card ranks shift +1 at flop, turn, and river.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { flop: ["incrementAllHoleRanks"], turn: ["incrementAllHoleRanks"], river: ["incrementAllHoleRanks"] },
    infoFeatures: ["card-drift"],
    score: "high",
  },
  {
    id: "recursive-board",
    name: "Recursive Board",
    shortName: "Recursive",
    summary: "At turn, the board duplicates itself.",
    detail: "The board recursively mirrors into ten displayed cards at turn.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "mirror" },
      visibleCommunityCards: { flop: 3, turn: 10, river: 10, reveal: 10 },
      scoreCommunityCards: 5,
    },
    phaseEffects: { turn: ["mirrorCommunity"] },
    infoFeatures: ["recursive-board"],
    score: "high",
  },
  {
    id: "mirror-hand",
    name: "Mirror Hand",
    shortName: "M Hand",
    summary: "Every hand has a shadow inversion.",
    detail: "Hole cards carry alternate identities so each hand can resolve through its mirrored possibility.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "holes" },
    identityResolution: "bestPossible",
    infoFeatures: ["mirror-hand"],
    score: "high",
  },
  {
    id: "twin-universes",
    name: "Twin Universes",
    shortName: "Twin U",
    summary: "Two board universes play out side-by-side.",
    detail: "Ten community cards form two five-card boards; each hand scores against its better universe.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      communityCards: 10,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "vault" },
      visibleCommunityCards: { flop: 5, turn: 10, river: 10, reveal: 10 },
      boards: { count: 2, cardsPerBoard: 5, scoring: "best" },
    },
    infoFeatures: ["twin-universes"],
    score: "high",
  },
  {
    id: "mirror-world",
    name: "Mirror World",
    shortName: "M World",
    summary: "Two realities are visible before reveal picks a ranking.",
    detail: "Two five-card boards are shown, with hands scored against their better reality.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      communityCards: 10,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "mirror" },
      visibleCommunityCards: { flop: 5, turn: 5, river: 10, reveal: 10 },
      boards: { count: 2, cardsPerBoard: 5, scoring: "best" },
    },
    infoFeatures: ["mirror-world"],
    score: "high",
  },
  {
    id: "card-constellation",
    name: "Card Constellation",
    shortName: "Constellation",
    summary: "Table-wide patterns create rank bonuses.",
    detail: "Sevens are treated as a constellation rank and can resolve as wild cards.",
    tags: ["insanity", "patterns"],
    deal: standardDeal,
    wildCards: { ranks: ["7"] },
    infoFeatures: ["card-constellation"],
    score: "high",
  },
  {
    id: "card-karma",
    name: "Card Karma",
    shortName: "Karma",
    summary: "A previous-round card echoes into this hand.",
    detail: "The first playable pass exposes a karma notice; cross-round card persistence is deferred.",
    tags: ["insanity", "memory"],
    deal: standardDeal,
    infoFeatures: ["card-karma"],
    score: "high",
  },
  {
    id: "card-resurrection",
    name: "Card Resurrection",
    shortName: "Resurrect",
    summary: "Discarded cards reappear as community cards.",
    detail: "Each hand is dealt three, keeps two automatically, and the discarded cards join the board at reveal.",
    tags: ["insanity", "discards"],
    deal: { ...standardDeal, holeCards: 3, keepCards: 2, discardedCardsToCommunity: true, visibleCommunityCards: { reveal: 22 } },
    infoFeatures: ["card-resurrection"],
    score: "high",
  },
  {
    id: "card-memorial",
    name: "Card Memorial",
    shortName: "Memorial",
    summary: "Old discards are remembered on the board.",
    detail: "A sixth memorial community card appears at reveal as the first playable memorial representation.",
    tags: ["insanity", "memory"],
    deal: { ...standardDeal, communityCards: 6, visibleCommunityCards: { flop: 3, turn: 4, river: 5, reveal: 6 }, scoreCommunityCards: 5 },
    infoFeatures: ["card-memorial"],
    score: "high",
  },
  {
    id: "hex-card",
    name: "Hex Card",
    shortName: "Hex",
    summary: "A specific card forces its holder to last.",
    detail: "The cursed ace of hearts acts as the hex card and forces its holder below non-hexed hands.",
    tags: ["insanity", "absolute"],
    deal: { ...standardDeal, deck: "cursed" },
    forceRankByMeta: { last: "cursed" },
    infoFeatures: ["hex-card"],
    score: "high",
  },
  {
    id: "blessed-card-absolute",
    name: "Blessed Card Absolute",
    shortName: "Bless Abs",
    summary: "A specific card forces its holder to first.",
    detail: "The blessed ace of hearts acts as the absolute blessing and forces its holder above non-blessed hands.",
    tags: ["insanity", "absolute"],
    deal: { ...standardDeal, deck: "blessed" },
    forceRankByMeta: { first: "blessed" },
    infoFeatures: ["blessed-card-absolute"],
    score: "high",
  },
  {
    id: "doomsday-card",
    name: "Doomsday Card",
    shortName: "Doomsday",
    summary: "A sealed card transforms the whole table at river.",
    detail: "The deterministic doomsday effect inverts all ranks when river begins.",
    tags: ["insanity", "event"],
    deal: standardDeal,
    phaseEffects: { river: ["invertAllRanks"] },
    infoFeatures: ["doomsday-card"],
    score: "high",
  },
  {
    id: "card-cipher",
    name: "Card Cipher",
    shortName: "Cipher",
    summary: "At river, values are encoded through the river card.",
    detail: "Every rank shifts by the river card's rank index when river begins.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["cipherRanksWithRiver"] },
    infoFeatures: ["card-cipher"],
    score: "high",
  },
  {
    id: "card-decoy",
    name: "Card Decoy",
    shortName: "Decoy",
    summary: "Six community cards are dealt; one is a decoy that does not score, but the chip does not say which.",
    detail: "The felt grows to a six-card row across flop/turn/river and a chip warns that one community card does not score, but the decoy is not marked on the felt — players cannot identify it without inference.",
    tags: ["insanity", "decoy"],
    deal: { ...standardDeal, communityCards: 6, visibleCommunityCards: { flop: 4, turn: 5, river: 6, reveal: 6 }, scoreCommunityCards: 5 },
    infoFeatures: ["card-decoy"],
    score: "high",
  },
  {
    id: "card-static",
    name: "Card Static",
    shortName: "C Static",
    summary: "Cards flicker into new ranks as the hand progresses.",
    detail: "The first hole card and first board card shift upward each street.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { flop: ["staticFlickerFirstCards"], turn: ["staticFlickerFirstCards"], river: ["staticFlickerFirstCards"] },
    infoFeatures: ["card-static"],
    score: "high",
  },
  {
    id: "cell-division",
    name: "Cell Division",
    shortName: "Division",
    summary: "At reveal, every hand splits in two.",
    detail: "Each two-card hand divides into two one-card hands at reveal, and the ranking expands to include the split hands.",
    tags: ["insanity", "structure"],
    deal: standardDeal,
    phaseEffects: { reveal: ["splitHandsAtReveal"] },
    infoFeatures: ["cell-division"],
    score: "high",
  },
  {
    id: "card-schism",
    name: "Card Schism",
    shortName: "Schism",
    summary: "At turn, the remaining deck splits high.",
    detail: "Future event draws come only from the high half of the deck after turn.",
    tags: ["insanity", "deck"],
    deal: standardDeal,
    phaseEffects: { turn: ["schismDeckHighOnly"] },
    infoFeatures: ["card-schism"],
    score: "high",
  },
  {
    id: "card-pendulum",
    name: "Card Pendulum",
    shortName: "Pendulum",
    summary: "The wild rank swings through the hand.",
    detail: "Sevens are the deterministic pendulum wild rank for this playable pass.",
    tags: ["insanity", "wild"],
    deal: standardDeal,
    wildCards: { ranks: ["7"] },
    infoFeatures: ["card-pendulum"],
    score: "high",
  },
  {
    id: "card-pinball",
    name: "Card Pinball",
    shortName: "Pinball",
    summary: "A community card bounces into a hole slot.",
    detail: "The first community card swaps with the first hole card at flop, turn, and river.",
    tags: ["insanity", "movement"],
    deal: standardDeal,
    phaseEffects: { flop: ["swapFirstHoleWithFirstCommunity"], turn: ["swapFirstHoleWithFirstCommunity"], river: ["swapFirstHoleWithFirstCommunity"] },
    infoFeatures: ["card-pinball"],
    score: "high",
  },
  {
    id: "card-inheritance",
    name: "Card Inheritance",
    shortName: "Inherit",
    summary: "Discards inherit from the board before disappearing.",
    detail: "Hands are dealt three and keep two automatically while a public inheritance hint tracks the disappearing discard rule.",
    tags: ["insanity", "discards"],
    deal: { ...standardDeal, holeCards: 3, keepCards: 2 },
    infoFeatures: ["card-inheritance"],
    score: "high",
  },
  {
    id: "doppelganger-deck",
    name: "Doppelganger Deck",
    shortName: "Doppel",
    summary: "Every card has a hidden twin somewhere else.",
    detail: "The deck is doubled so duplicate identities can appear across hands and board.",
    tags: ["insanity", "deck"],
    deal: { ...standardDeal, deck: "double" },
    infoFeatures: ["doppelganger-deck"],
    score: "high",
  },
  {
    id: "telepathic-river",
    name: "Telepathic River",
    shortName: "Telepathy",
    summary: "At river, the table feels a neighbor-card hint.",
    detail: "The river broadcast carries a vague public neighbor-card hint while scoring stays unchanged.",
    tags: ["insanity", "info"],
    deal: standardDeal,
    infoFeatures: ["telepathic-river"],
    score: "high",
  },
  {
    id: "card-whisper",
    name: "Card Whisper",
    shortName: "Whisper",
    summary: "Only the river shows a public Tell chip with one true board fact.",
    detail: "In the verified run, no chip appeared before river; river showed `Tell Board card 1 is 8D`, and the first board card was 8D.",
    tags: ["insanity", "info"],
    deal: standardDeal,
    infoFeatures: ["card-whisper"],
    score: "high",
  },
  {
    id: "card-lunar",
    name: "Card Lunar",
    shortName: "Lunar",
    summary: "One suit waxes in strength.",
    detail: "Hearts are the deterministic waxing lunar suit and resolve as wild cards.",
    tags: ["insanity", "suits"],
    deal: standardDeal,
    wildCards: { suits: ["H"] },
    infoFeatures: ["card-lunar"],
    score: "high",
  },
  {
    id: "pandemonium",
    name: "Pandemonium",
    shortName: "Pandemonium",
    summary: "A different chaos effect fires each phase.",
    detail: "The deterministic capstone fires rank shift, rank vortex, and rank inversion across flop, turn, and river.",
    tags: ["insanity", "capstone"],
    deal: { ...standardDeal, possibleIdentities: "holesAndBoard" },
    identityResolution: "bestPossible",
    phaseEffects: { flop: ["incrementAllRanks"], turn: ["rotateHoleRanksAcrossHands"], river: ["invertAllRanks"] },
    infoFeatures: ["pandemonium"],
    score: "high",
  },
  {
    id: "lowball",
    name: "Lowball Ding",
    shortName: "Lowball",
    summary: "The worst poker hand wins the top slot.",
    detail: "Ranking instincts invert: weak high-card hands become the hands to protect.",
    tags: ["inverted", "mind-bending"],
    deal: standardDeal,
    score: "lowball",
  },
  {
    id: "omaha-luxe",
    name: "Omaha Luxe",
    shortName: "Omaha",
    summary: "Four private cards per hand, best five-card poker hand wins.",
    detail: "More private information creates bigger late-street reversals and tougher negotiation.",
    tags: ["big-hands", "complex"],
    deal: { ...standardDeal, holeCards: 4 },
    score: "high",
  },
  {
    id: "pent",
    name: "Pent",
    shortName: "Pent",
    summary: "Five private cards per hand make every hand information-dense.",
    detail: "Each hand starts with five hole cards, then still uses the shared board to find its best five-card poker hand.",
    tags: ["big-hands", "dense"],
    deal: { ...standardDeal, holeCards: 5 },
    score: "high",
  },
  {
    id: "solitaire-suite",
    name: "Solitaire Suite",
    shortName: "Solitaire",
    summary: "Seven private cards per hand; the board is mostly a side dish.",
    detail: "Every hand gets seven hole cards and scores the best five-card poker hand available with the board.",
    tags: ["big-hands", "solo"],
    deal: { ...standardDeal, holeCards: 7 },
    score: "high",
  },
  {
    id: "players-choice",
    name: "Player's Choice",
    shortName: "Choice",
    summary: "Every hand is dealt three cards; the owner keeps any two before ranking starts.",
    detail: "A deal-choice phase lets each player sculpt their starting hands, then the game continues as classic Ding.",
    tags: ["choice", "deal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 3, keepCards: 2, selectionPhase: true },
    },
    score: "high",
  },
  {
    id: "pick-2-of-5",
    name: "Pick 2 of 5",
    shortName: "Pick 2",
    summary: "Every hand is dealt five cards; the owner keeps any two before ranking starts.",
    detail: "A deeper deal-choice phase gives each player five private candidates and asks them to sculpt a two-card start.",
    tags: ["choice", "deal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 5, keepCards: 2, selectionPhase: true },
    },
    score: "high",
  },
  {
    id: "pick-3-of-7",
    name: "Pick 3 of 7",
    shortName: "Pick 3",
    summary: "Every hand is dealt seven cards; the owner keeps any three before ranking starts.",
    detail: "A heavy deal-choice phase gives each player seven private candidates and asks them to sculpt a three-card start.",
    tags: ["choice", "big-hands"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 7, keepCards: 3, selectionPhase: true },
    },
    score: "high",
  },
  {
    id: "mulligan",
    name: "Mulligan",
    shortName: "Mulligan",
    summary: "Every hand may refuse its first two cards once and redraw before ranking starts.",
    detail: "A deal-choice phase lets each hand either lock its original two-card start or spend a one-time full redraw.",
    tags: ["choice", "redeal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 2, keepCards: 2, selectionPhase: true, mulligan: true },
    },
    score: "high",
  },
  {
    id: "trade-up",
    name: "Trade-Up",
    shortName: "Trade-Up",
    summary: "At the deal, each hand passes one selected card to the left neighbor.",
    detail: "Every owner chooses one hole card to trade away. Cards move simultaneously around the table before preflop ranking starts.",
    tags: ["choice", "trade"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 2, keepCards: 1, selectionPhase: true, tradeUp: true },
    },
    score: "high",
  },
  {
    id: "inheritance",
    name: "Inheritance",
    shortName: "Inherit",
    summary: "Keep one hole card; your second card comes from the right neighbor's discard.",
    detail: "Every owner chooses one card to keep. The other card is discarded left, so each final hand combines one kept card with the right neighbor's discarded card.",
    tags: ["choice", "deal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 2, keepCards: 1, selectionPhase: true, inheritance: true },
    },
    score: "high",
  },
  {
    id: "look-then-choose",
    name: "Look-Then-Choose",
    shortName: "Look",
    summary: "Peek three deal cards and keep any two before ranking starts.",
    detail: "Each hand sees three private candidates from the deck, chooses two to keep, and starts preflop with that sculpted two-card hand.",
    tags: ["choice", "deal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 3, keepCards: 2, selectionPhase: true },
    },
    score: "high",
  },
  {
    id: "echo",
    name: "Echo",
    shortName: "Echo",
    summary: "Both hole cards in every hand share a rank.",
    detail: "Every hand starts as a pocket pair, creating dense rank collisions and sharper kicker races through the board.",
    tags: ["constrained", "pairs"],
    deal: { ...standardDeal, constraint: "pocketPair" },
    score: "high",
  },
  {
    id: "mirror-match",
    name: "Mirror Match",
    shortName: "Mirror",
    summary: "Every hand shares the same first hole card.",
    detail: "A single mirrored anchor card appears in every hand, so the second hole card and board texture decide the spread.",
    tags: ["constrained", "mirror"],
    deal: { ...standardDeal, constraint: "sharedFirstCard" },
    score: "high",
  },
  {
    id: "rainbow-hole",
    name: "Rainbow Hole",
    shortName: "Rainbow",
    summary: "Hole cards in every hand are guaranteed different suits.",
    detail: "Every hand starts with two suits represented, reducing suited-hole certainty while keeping classic high-hand scoring.",
    tags: ["constrained", "suits"],
    deal: { ...standardDeal, constraint: "differentSuits" },
    score: "high",
  },
  {
    id: "suited-hole",
    name: "Suited Hole",
    shortName: "Suited",
    summary: "Hole cards in every hand are guaranteed the same suit.",
    detail: "Every hand starts suited, making flush paths more visible without changing classic high-hand scoring.",
    tags: ["constrained", "suits"],
    deal: { ...standardDeal, constraint: "sameSuit" },
    score: "high",
  },
  {
    id: "connected-hole",
    name: "Connected Hole",
    shortName: "Connected",
    summary: "Hole cards in every hand are guaranteed adjacent ranks.",
    detail: "Every hand starts with neighboring ranks, creating visible straight paths while keeping classic high-hand scoring.",
    tags: ["constrained", "ranks"],
    deal: { ...standardDeal, constraint: "connectedRanks" },
    score: "high",
  },
  {
    id: "gapped-hole",
    name: "Gapped Hole",
    shortName: "Gapped",
    summary: "Hole cards in every hand are guaranteed two ranks apart.",
    detail: "Every hand starts with a one-rank gap between its cards, creating less direct straight texture than Connected Hole.",
    tags: ["constrained", "ranks"],
    deal: { ...standardDeal, constraint: "gappedRanks" },
    score: "high",
  },
  {
    id: "polar-hole",
    name: "Polar Hole",
    shortName: "Polar",
    summary: "Every hand starts with one high card and one low card.",
    detail: "Each two-card hand is split between the 8-A high band and the 2-7 low band, creating visible kicker asymmetry.",
    tags: ["constrained", "ranks"],
    deal: { ...standardDeal, constraint: "polarRanks" },
    score: "high",
  },
  {
    id: "twin-spark",
    name: "Twin Spark",
    shortName: "Twin",
    summary: "Both hole cards in every hand come from the low ranks.",
    detail: "Every hand starts with two cards from 2 through 7, compressing early strength and making board improvement matter more.",
    tags: ["constrained", "low"],
    deal: { ...standardDeal, constraint: "lowRanks" },
    score: "high",
  },
  {
    id: "royal-spark",
    name: "Royal Spark",
    shortName: "Royal",
    summary: "Both hole cards in every hand come from the high ranks.",
    detail: "Every hand starts with two cards from 8 through Ace, making preflop strength dense and board kickers sharper.",
    tags: ["constrained", "high"],
    deal: { ...standardDeal, constraint: "highRanks" },
    score: "high",
  },
  {
    id: "triad",
    name: "Triad",
    shortName: "Triad",
    summary: "Three private cards per hand, best five-card poker hand wins.",
    detail: "A lighter multi-card mode with enough extra texture to make rankings less obvious.",
    tags: ["big-hands", "swingy"],
    deal: { ...standardDeal, holeCards: 3 },
    score: "high",
  },
  {
    id: "single-spark",
    name: "Single Spark",
    shortName: "Spark",
    summary: "Each hand gets one private card instead of two.",
    detail: "Tiny private edges make public-board reading and player confidence matter more.",
    tags: ["minimal", "fast"],
    deal: { ...standardDeal, holeCards: 1 },
    score: "high",
  },
  {
    id: "double-river",
    name: "Double River",
    shortName: "2 River",
    summary: "The river reveals two final community cards.",
    detail: "Six-card boards create dramatic final re-sorts without changing the core loop.",
    tags: ["late-swing", "board"],
    deal: {
      holeCards: 2,
      communityCards: 6,
      visibleCommunityCards: { ...baseVisibleCommunity, river: 6, reveal: 6 },
    },
    score: "high",
  },
  {
    id: "big-sky",
    name: "Big Sky",
    shortName: "Big Sky",
    summary: "A seven-card board gives every hand more ways to connect.",
    detail: "The board grows to four on the flop, five on the turn, and seven on the river.",
    tags: ["board", "chaotic"],
    deal: {
      holeCards: 2,
      communityCards: 7,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 4, turn: 5, river: 7, reveal: 7 },
    },
    score: "high",
  },
  {
    id: "tiny-board",
    name: "Tiny Board",
    shortName: "Tiny",
    summary: "Only three community cards are dealt.",
    detail: "The flop is the whole board, so private cards matter longer and there is no late board rescue.",
    tags: ["board", "small"],
    deal: {
      holeCards: 2,
      communityCards: 3,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 3, river: 3, reveal: 3 },
    },
    score: "high",
  },
  {
    id: "mini-board",
    name: "Mini Board",
    shortName: "Mini",
    summary: "Four community cards are dealt.",
    detail: "The board gets a normal flop and one turn card, then stays fixed through river.",
    tags: ["board", "small"],
    deal: {
      holeCards: 2,
      communityCards: 4,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 4, reveal: 4 },
    },
    score: "high",
  },
  {
    id: "behemoth",
    name: "Behemoth",
    shortName: "Behemoth",
    summary: "Nine community cards are dealt; best five-card poker hand wins.",
    detail: "The river dumps the rest of a huge board, creating a crowded final comparison across eleven available cards.",
    tags: ["board", "huge"],
    deal: {
      holeCards: 2,
      communityCards: 9,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 9, reveal: 9 },
    },
    score: "high",
  },
  {
    id: "two-boards",
    name: "Two Boards",
    shortName: "2 Boards",
    summary: "Two parallel boards are dealt; every hand scores against its better board.",
    detail: "Each street reveals cards on both boards, and showdown evaluates every hand on both boards before keeping its strongest result.",
    tags: ["board", "multi-board"],
    deal: {
      holeCards: 2,
      communityCards: 10,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "vault" },
      boards: { count: 2, cardsPerBoard: 5, scoring: "best" },
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 6, turn: 8, river: 10, reveal: 10 },
    },
    score: "high",
  },
  {
    id: "split-board",
    name: "Split Board",
    shortName: "Split",
    summary: "Six community cards form two three-card halves; every hand scores on its better half.",
    detail: "The whole split board lands together, but each hand only combines with one side at showdown.",
    tags: ["board", "multi-board"],
    deal: {
      holeCards: 2,
      communityCards: 6,
      boardLayout: { kind: "dual", primary: 3, secondary: 3, secondaryRole: "vault" },
      boards: { count: 2, cardsPerBoard: 3, scoring: "best" },
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 6, turn: 6, river: 6, reveal: 6 },
    },
    score: "high",
  },
  {
    id: "tower",
    name: "Tower",
    shortName: "Tower",
    summary: "A five-card stack shows only its top three cards until river.",
    detail: "The table reads a stable three-card board through turn, then the hidden bottom of the stack appears at river.",
    tags: ["board", "hidden"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 3, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "cross",
    name: "Cross",
    shortName: "Cross",
    summary: "Five community cards form a cross; every hand scores on its better line.",
    detail: "The center card belongs to both the row and the column, so hands can connect along either axis.",
    tags: ["board", "shape"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      boardLayout: { kind: "grid", slots: [
        { row: 1, col: 0 },
        { row: 0, col: 1 },
        { row: 1, col: 1, group: "center" },
        { row: 2, col: 1 },
        { row: 1, col: 2 },
      ] },
      boards: {
        cardIndexes: [[0, 2, 4], [1, 2, 3]],
        scoring: "best",
      },
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "l-board",
    name: "L-Board",
    shortName: "L-Board",
    summary: "Seven community cards form an L; every hand scores on its best five-card path.",
    detail: "The L is scored as overlapping five-card paths along the bend, creating several possible board lanes.",
    tags: ["board", "shape"],
    deal: {
      holeCards: 2,
      communityCards: 7,
      boardLayout: { kind: "L", arm: 5, stem: 3 },
      boards: {
        cardIndexes: [[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6]],
        scoring: "best",
      },
      visibleCommunityIndexes: {
        lobby: [],
        preflop: [],
        flop: [0, 1, 2, 5, 6],
        turn: [0, 1, 2, 3, 5, 6],
        river: [0, 1, 2, 3, 4, 5, 6],
        reveal: [0, 1, 2, 3, 4, 5, 6],
      },
    },
    score: "high",
  },
  {
    id: "flash-flop",
    name: "Flash Flop",
    shortName: "Flash",
    summary: "The flop is visible before anyone ranks a hand.",
    detail: "Players start with real board context, so early rankings are less random.",
    tags: ["information", "fast"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { ...baseVisibleCommunity, preflop: 3 },
    },
    score: "high",
  },
  {
    id: "flash-river",
    name: "Flash River",
    shortName: "Flash R",
    summary: "The full board is visible before anyone ranks a hand.",
    detail: "All five community cards are public at preflop, turning the whole hand into immediate table-reading.",
    tags: ["information", "board"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { ...baseVisibleCommunity, preflop: 5, flop: 5, turn: 5, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "blackout",
    name: "Blackout",
    shortName: "Blackout",
    summary: "No community cards are shown until the river.",
    detail: "The first three streets are pure private-hand debate, then the board lands all at once.",
    tags: ["bluff", "suspense"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 0, turn: 0, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "slow-burn",
    name: "Slow Burn",
    shortName: "Slow",
    summary: "The board arrives one card, then three, then five.",
    detail: "A narrow flop makes early confidence brittle and keeps trades alive longer.",
    tags: ["suspense", "board"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 1, turn: 3, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "turnpike",
    name: "Turnpike",
    shortName: "Turnpike",
    summary: "Four community cards hit on the flop, then the game pauses before the river.",
    detail: "Most of the board appears early, making the final card a sharper negotiation point.",
    tags: ["board", "tempo"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 4, turn: 4, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "crawl",
    name: "Crawl",
    shortName: "Crawl",
    summary: "The board crawls out slowly before completing at river.",
    detail: "One card is visible preflop, then the board inches forward before the final two cards arrive at river.",
    tags: ["board", "slow"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 1, flop: 2, turn: 3, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "eclipse-suit",
    name: "Eclipse Suit",
    shortName: "Eclipse S",
    summary: "Community cards show suits only until reveal.",
    detail: "The board's suit texture is visible, but ranks stay hidden until the final reveal.",
    tags: ["visibility", "suits"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetail: { preflop: "suit", flop: "suit", turn: "suit", river: "suit" },
    },
    score: "high",
  },
  {
    id: "eclipse-rank",
    name: "Eclipse Rank",
    shortName: "Eclipse R",
    summary: "Community cards show ranks only until reveal.",
    detail: "The board's rank structure is visible, but suits stay hidden until the final reveal.",
    tags: ["visibility", "ranks"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetail: { preflop: "rank", flop: "rank", turn: "rank", river: "rank" },
    },
    score: "high",
  },
  {
    id: "eclipse-color",
    name: "Eclipse Color",
    shortName: "Eclipse C",
    summary: "Community cards show only red or black until reveal.",
    detail: "The board exposes color pressure while hiding exact ranks and suits until the final reveal.",
    tags: ["visibility", "color"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetail: { preflop: "color", flop: "color", turn: "color", river: "color" },
    },
    score: "high",
  },
  {
    id: "dark-river",
    name: "Dark River",
    shortName: "Dark R",
    summary: "The river card shows only its suit until reveal.",
    detail: "The first four board cards are normal, but the final river card keeps its rank hidden until reveal.",
    tags: ["visibility", "river"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetails: { river: { 4: "suit" } },
    },
    score: "high",
  },
  {
    id: "dark-flop",
    name: "Dark Flop",
    shortName: "Dark F",
    summary: "The flop stays face-down until turn.",
    detail: "No community cards are visible at flop; the board catches up at turn.",
    tags: ["visibility", "flop"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 0, turn: 4, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "hidden-turn",
    name: "Hidden Turn",
    shortName: "Hidden T",
    summary: "The turn card stays hidden until river.",
    detail: "The flop is visible, but the fourth board card is withheld until the river reveal catches up.",
    tags: ["visibility", "turn"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 3, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "confirm-flop",
    name: "Confirm Flop",
    shortName: "Confirm",
    summary: "The flop is hidden, then confirmed all at once on turn.",
    detail: "The table ranks preflop and flop without board cards, then the flop and turn appear together.",
    tags: ["visibility", "flop"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 0, turn: 4, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "two-step-river",
    name: "Two-Step River",
    shortName: "2-Step",
    summary: "The river has two final cards; one waits until reveal.",
    detail: "A sixth board card is dealt, but only one of the two final river cards is visible before reveal.",
    tags: ["visibility", "river"],
    deal: {
      holeCards: 2,
      communityCards: 6,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 5, reveal: 6 },
    },
    score: "high",
  },
  {
    id: "random-replace",
    name: "Random Replace",
    shortName: "Replace",
    summary: "At turn, one visible board card is swapped for a fresh card.",
    detail: "The board mutates as the turn begins, forcing the table to re-evaluate earlier placements.",
    tags: ["board", "event"],
    deal: standardDeal,
    phaseEffects: { turn: ["randomReplaceVisibleCommunity"] },
    score: "high",
  },
  {
    id: "cascade",
    name: "Cascade",
    shortName: "Cascade",
    summary: "The oldest visible board cards fade face-down as streets advance.",
    detail: "One more early community card becomes unknown at each board street, while reveal restores the true board.",
    tags: ["visibility", "board"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetails: {
        flop: { 0: "hidden" },
        turn: { 0: "hidden", 1: "hidden" },
        river: { 0: "hidden", 1: "hidden", 2: "hidden" },
      },
    },
    score: "high",
  },
  {
    id: "reversal",
    name: "Reversal",
    shortName: "Reverse",
    summary: "At river, the board reverses in place.",
    detail: "The same five community cards remain in play, but their displayed order flips when the river phase begins.",
    tags: ["board", "event"],
    deal: standardDeal,
    phaseEffects: { river: ["reverseCommunity"] },
    score: "high",
  },
  {
    id: "mirror-board",
    name: "Mirror Board",
    shortName: "Mirror",
    summary: "At river, the board appears as two mirrored five-card rows.",
    detail: "In the verified run, river rendered ten community slots split into primary and mirror rows while showdown still scored against the five primary cards.",
    tags: ["board", "large"],
    deal: {
      ...standardDeal,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "mirror" },
      visibleCommunityCards: { lobby: 0, dealChoice: 0, preflop: 0, flop: 3, turn: 4, river: 10, reveal: 10 },
      scoreCommunityCards: 5,
    },
    phaseEffects: { river: ["mirrorCommunity"] },
    score: "high",
  },
  {
    id: "vault-card",
    name: "Vault Card",
    shortName: "Vault",
    summary: "A sixth card waits in a separate Vault lane until reveal.",
    detail: "In the verified run, river showed five primary board cards plus an empty `VAULT` lane, and reveal exposed the sixth community card in that lane.",
    tags: ["visibility", "reveal"],
    deal: {
      holeCards: 2,
      communityCards: 6,
      boardLayout: { kind: "dual", primary: 5, secondary: 1, secondaryRole: "vault" },
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 5, reveal: 6 },
    },
    score: "high",
  },
  {
    id: "phoenix-board",
    name: "Phoenix Board",
    shortName: "Phoenix",
    summary: "Discarded third hole cards rise into a reveal-only Vault row.",
    detail: "In the verified eight-hand run, reveal kept the five-card primary board and showed eight returned discard cards in the `VAULT` row.",
    tags: ["deal", "board"],
    deal: {
      holeCards: 3,
      keepCards: 2,
      communityCards: 5,
      boardLayout: { kind: "dual", primary: 5, secondary: 17, secondaryRole: "vault" },
      discardedCardsToCommunity: true,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 5, reveal: 22 },
    },
    score: "high",
  },
  {
    id: "flush-hunt",
    name: "Flush Hunt",
    shortName: "Flush",
    summary: "Hands rank by the largest same-suit cluster first.",
    detail: "Poker strength breaks ties, but suit density is the primary objective.",
    tags: ["objective", "suits"],
    deal: standardDeal,
    score: "flush",
  },
  {
    id: "straight-hunt",
    name: "Straight Hunt",
    shortName: "Straight",
    summary: "Hands rank by their longest rank run first.",
    detail: "Poker strength breaks ties, but connected cards define the table order.",
    tags: ["objective", "ranks"],
    deal: standardDeal,
    score: "straight",
  },
  {
    id: "pair-party",
    name: "Pair Party",
    shortName: "Pairs",
    summary: "Pairs, trips, and quads are the main scoring target.",
    detail: "The best multiplicity profile wins, with normal poker strength as the tiebreaker.",
    tags: ["objective", "ranks"],
    deal: standardDeal,
    score: "pairs",
  },
  {
    id: "red-shift",
    name: "Red Shift",
    shortName: "Red",
    summary: "Red cards are the primary scoring resource.",
    detail: "More hearts and diamonds rank higher; poker strength breaks close red counts.",
    tags: ["objective", "color"],
    deal: standardDeal,
    score: "red",
  },
  {
    id: "black-ice",
    name: "Black Ice",
    shortName: "Black",
    summary: "Black cards are the primary scoring resource.",
    detail: "More clubs and spades rank higher; poker strength breaks close black counts.",
    tags: ["objective", "color"],
    deal: standardDeal,
    score: "black",
  },
] as const;
