import type { DingGameModeDefinition } from "./types";
import { baseVisibleCommunity, standardDeal } from "./types";

export const GAME_MODE_DEFINITIONS: readonly DingGameModeDefinition[] = [
  {
    id: "ding",
    name: "Classic Ding",
    shortName: "Classic",
    summary: "The original cooperative hold'em ranking game.",
    detail: "Two private cards, five shared board cards, strongest poker hand wins.",
    tags: ["core", "balanced"],
    deal: standardDeal,
    score: "high",
  },
  {
    id: "draw-three",
    name: "Draw 3, Discard 1",
    shortName: "Draw 3",
    summary: "Every hand is dealt three cards and automatically keeps its best two-card start.",
    detail: "The discard happens before pre-flop so players still coordinate with two-card hands.",
    tags: ["choice", "discards"],
    deal: { ...standardDeal, holeCards: 3, keepCards: 2 },
    score: "high",
  },
  {
    id: "one-up",
    name: "One Up",
    shortName: "One Up",
    summary: "One card from every hand is public from the start.",
    detail: "The exposed card gives the table shared anchors without revealing the full hand.",
    tags: ["visibility", "holes"],
    deal: { ...standardDeal, publicCards: 1 },
    score: "high",
  },
  {
    id: "open-book",
    name: "Open Book",
    shortName: "Open",
    summary: "Everyone's hole cards are public.",
    detail: "A low-bluff, high-coordination mode where disagreements are about interpretation.",
    tags: ["visibility", "holes"],
    deal: { ...standardDeal, publicCards: 2 },
    score: "high",
  },
  {
    id: "late-light",
    name: "Late Light",
    shortName: "Late",
    summary: "Hole cards become public at the river.",
    detail: "Hands stay private through turn, then every hole card is exposed at river before the final ranking.",
    tags: ["visibility", "river"],
    deal: { ...standardDeal, visibleHoleCards: { river: 2, reveal: 2 } },
    score: "high",
  },
  {
    id: "suit-showing",
    name: "Suit Showing",
    shortName: "Suits",
    summary: "Every hole-card suit is public, but ranks stay hidden.",
    detail: "The table sees suit texture from the deal while actual ranks remain private until reveal.",
    tags: ["visibility", "suits"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 },
      visibleHoleCardDetail: "suit",
    },
    score: "high",
  },
  {
    id: "rank-showing",
    name: "Rank Showing",
    shortName: "Ranks",
    summary: "Every hole-card rank is public, but suits stay hidden.",
    detail: "The table sees paired and high-card structure from the deal while exact suits remain private until reveal.",
    tags: ["visibility", "ranks"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 },
      visibleHoleCardDetail: "rank",
    },
    score: "high",
  },
  {
    id: "color-showing",
    name: "Color Showing",
    shortName: "Colors",
    summary: "Every hole-card color is public, but ranks and suits stay hidden.",
    detail: "The table sees red/black texture from the deal while exact ranks and suits remain private until reveal.",
    tags: ["visibility", "colors"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 },
      visibleHoleCardDetail: "color",
    },
    score: "high",
  },
  {
    id: "brightest-out",
    name: "Brightest Out",
    shortName: "Brightest",
    summary: "The highest hole card in every hand is public from the start.",
    detail: "Each hand exposes its brightest private card, giving the table a high-card anchor while the lower card stays hidden until reveal.",
    tags: ["visibility", "holes"],
    deal: { ...standardDeal, publicCards: 1, publicCardSelection: "highest" },
    score: "high",
  },
  {
    id: "darkest-out",
    name: "Darkest Out",
    shortName: "Darkest",
    summary: "The lowest hole card in every hand is public from the start.",
    detail: "Each hand exposes its darkest private card, giving the table a low-card anchor while the higher card stays hidden until reveal.",
    tags: ["visibility", "holes"],
    deal: { ...standardDeal, publicCards: 1, publicCardSelection: "lowest" },
    score: "high",
  },
  {
    id: "short-deck",
    name: "Short Deck",
    shortName: "Short",
    summary: "Cards two through five are removed before the deal.",
    detail: "Compressed ranks make strong hands common and hand reading more volatile.",
    tags: ["deck", "compact"],
    deal: { ...standardDeal, deck: "short" },
    score: "high",
  },
  {
    id: "stripped",
    name: "Stripped",
    shortName: "Stripped",
    summary: "Only ranks 8 through ace are in the deck.",
    detail: "The deck compresses to twenty-eight high cards, making premium holdings and collisions common.",
    tags: ["deck", "compact"],
    deal: { ...standardDeal, deck: "stripped" },
    score: "high",
  },
  {
    id: "bottom-half",
    name: "Bottom Half",
    shortName: "Bottom",
    summary: "Only ranks two through nine are in the deck.",
    detail: "The deck removes broadway texture and makes low-rank board reading much sharper.",
    tags: ["deck", "ranks"],
    deal: { ...standardDeal, deck: "bottomHalf" },
    score: "high",
  },
  {
    id: "double-deck",
    name: "Double Deck",
    shortName: "Double",
    summary: "Two full decks are merged before the deal.",
    detail: "Duplicate identities can appear, increasing rank collisions and strange shared-outs.",
    tags: ["deck", "duplicates"],
    deal: { ...standardDeal, deck: "double" },
    score: "high",
  },
  {
    id: "triple-deck",
    name: "Triple Deck",
    shortName: "Triple",
    summary: "Three full decks are merged before the deal.",
    detail: "The enlarged deck makes exact duplicate cards possible while preserving cooperative ranking.",
    tags: ["deck", "duplicates"],
    deal: { ...standardDeal, deck: "triple" },
    score: "high",
  },
  {
    id: "half-deck",
    name: "Half Deck",
    shortName: "Half",
    summary: "A random twenty-six-card deck is used for the whole hand.",
    detail: "Half the deck is removed before dealing, creating a tight and unpredictable card pool.",
    tags: ["deck", "compact"],
    deal: { ...standardDeal, deck: "half" },
    score: "high",
  },
  {
    id: "pinochle",
    name: "Pinochle",
    shortName: "Pinochle",
    summary: "Ranks nine through ace appear twice in each suit.",
    detail: "A duplicated high-card deck creates compact, collision-heavy boards and hands.",
    tags: ["deck", "duplicates"],
    deal: { ...standardDeal, deck: "pinochle" },
    score: "high",
  },
  {
    id: "tarot",
    name: "Tarot",
    shortName: "Tarot",
    summary: "Two arcana cards are shuffled into the deck and play as wild cards.",
    detail: "Whichever hand or board picks up an arcana card can read it as the strongest identity available at reveal.",
    tags: ["deck", "wild"],
    deal: { ...standardDeal, deck: "tarot" },
    wildCards: { metas: ["tarot"] },
    score: "high",
  },
  {
    id: "suit-heavy",
    name: "Suit-Heavy",
    shortName: "Heavy",
    summary: "Hearts are doubled in the deck, making heart flushes far more common.",
    detail: "The heart suit appears twice as often, biasing every street toward red flush draws while ranks stay normal.",
    tags: ["deck", "suits"],
    deal: { ...standardDeal, deck: "suitHeavy" },
    score: "high",
  },
  {
    id: "suit-light",
    name: "Suit-Light",
    shortName: "Light",
    summary: "Hearts are trimmed to six cards in the deck, making heart flushes scarce.",
    detail: "Most hearts are removed before the deal so red flush draws rarely materialize while the other suits stay intact.",
    tags: ["deck", "suits"],
    deal: { ...standardDeal, deck: "suitLight" },
    score: "high",
  },
  {
    id: "inverted-deck",
    name: "Inverted Deck",
    shortName: "Invert",
    summary: "Aces are low and twos rank above kings.",
    detail: "Showdown maps rank strength through an inverted order before comparing poker hands.",
    tags: ["identity", "ranks"],
    deal: standardDeal,
    rankTransform: "inverted",
    score: "high",
  },
  {
    id: "jokers-in",
    name: "Jokers In",
    shortName: "Jokers",
    summary: "Two jokers are added to the deck as wild cards.",
    detail: "Each joker can become the best possible card identity for the hand holding it at showdown.",
    tags: ["deck", "wild"],
    deal: { ...standardDeal, deck: "jokers" },
    wildCards: { metas: ["joker"] },
    score: "high",
  },
  {
    id: "wild-suit",
    name: "Wild Suit",
    shortName: "Wild S",
    summary: "Every heart plays as a wild card at showdown.",
    detail: "Any heart in a hand or on the board can stand in for whichever rank or suit makes the strongest reveal hand.",
    tags: ["wild", "suits"],
    deal: standardDeal,
    wildCards: { suits: ["H"] },
    score: "high",
  },
  {
    id: "wild-rank",
    name: "Wild Rank",
    shortName: "Wild R",
    summary: "Every seven plays as a wild card at showdown.",
    detail: "Any seven in a hand or on the board can stand in for whichever rank or suit makes the strongest reveal hand.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["7"] },
    score: "high",
  },
  {
    id: "wild-rank-roulette",
    name: "Wild Rank Roulette",
    shortName: "Roulette",
    summary: "A new rank becomes wild each street; whichever is wild at reveal counts for showdown.",
    detail: "Fives, sixes, sevens, and eights take turns as the wild rank across flop, turn, river, and reveal; only the reveal-phase rank substitutes for scoring.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCardsByPhase: {
      flop: { ranks: ["5"] },
      turn: { ranks: ["6"] },
      river: { ranks: ["7"] },
      reveal: { ranks: ["8"] },
    },
    infoFeatures: ["wild-rank-roulette"],
    score: "high",
  },
  {
    id: "wild-aces",
    name: "Wild Aces",
    shortName: "Wild A",
    summary: "Aces are wild for showdown.",
    detail: "Every ace can substitute into the strongest available identity at reveal.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["A"] },
    score: "high",
  },
  {
    id: "wild-faces",
    name: "Wild Faces",
    shortName: "Faces",
    summary: "Jacks, queens, and kings are wild.",
    detail: "Face cards can substitute into stronger identities at reveal, creating volatile high-card and made-hand swings.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["J", "Q", "K"] },
    score: "high",
  },
  {
    id: "anti-wild",
    name: "Anti-Wild",
    shortName: "Anti",
    summary: "One announced rank is banned from scoring.",
    detail: "Sevens are ignored by the showdown evaluator, shrinking hands and boards before hand comparison.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    excludedRanks: ["7"],
    score: "high",
  },
  {
    id: "cursed-card",
    name: "Cursed Card",
    shortName: "Cursed",
    summary: "One cursed card is shuffled in; whichever hand holds it finishes last.",
    detail: "The cursed marker overrides poker strength at reveal, dropping the cursed hand below every uncursed hand regardless of made-hand quality.",
    tags: ["identity", "marked"],
    deal: { ...standardDeal, deck: "cursed" },
    forceRankByMeta: { last: "cursed" },
    score: "high",
  },
  {
    id: "blessed-card",
    name: "Blessed Card",
    shortName: "Blessed",
    summary: "One blessed card is shuffled in; whichever hand holds it finishes first.",
    detail: "The blessed marker overrides poker strength at reveal, lifting the blessed hand above every unblessed hand regardless of made-hand quality.",
    tags: ["identity", "marked"],
    deal: { ...standardDeal, deck: "blessed" },
    forceRankByMeta: { first: "blessed" },
    score: "high",
  },
  {
    id: "counterfeit",
    name: "Counterfeit",
    shortName: "Counter",
    summary: "One face-down hole card per hand is value zero.",
    detail: "The first kept hole card in every hand is marked counterfeit and ignored by showdown scoring.",
    tags: ["identity", "holes"],
    deal: { ...standardDeal, counterfeitHoleCards: 1 },
    excludedMetas: ["counterfeit"],
    score: "high",
  },
  {
    id: "glitch-card",
    name: "Glitch Card",
    shortName: "Glitch",
    summary: "One glitched card hides its identity, then resolves wild at reveal.",
    detail: "The glitched card's true rank and suit stay unknown until reveal, where it plays as a wild card for whichever hand holds it.",
    tags: ["wild", "marked"],
    deal: { ...standardDeal, deck: "glitch" },
    wildCards: { metas: ["glitched"] },
    score: "high",
  },
  {
    id: "two-suited-card",
    name: "Two-Suited Card",
    shortName: "2-Suit",
    summary: "One card carries two suits at once for flush purposes.",
    detail: "The marked card counts as whichever of its two suits makes the better flush at reveal, while its rank stays fixed.",
    tags: ["wild", "marked"],
    deal: { ...standardDeal, deck: "twoSuited" },
    wildCards: { metas: ["twoSuited"] },
    score: "high",
  },
  {
    id: "wild-connector",
    name: "Wild Connector",
    shortName: "Connect",
    summary: "Adjacent ranks can behave like a pair.",
    detail: "A connected rank pair creates a synthetic pair during showdown evaluation.",
    tags: ["identity", "ranks"],
    deal: standardDeal,
    syntheticPair: "adjacent",
    score: "high",
  },
  {
    id: "wild-spread",
    name: "Wild Spread",
    shortName: "Spread",
    summary: "Far-apart ranks can behave like a pair.",
    detail: "A wide rank spread creates a synthetic pair during showdown evaluation.",
    tags: ["identity", "ranks"],
    deal: standardDeal,
    syntheticPair: "spread",
    score: "high",
  },
  {
    id: "marked-deck",
    name: "Marked Deck",
    shortName: "Marked",
    summary: "One card carries a public marker the whole table can see.",
    detail: "The marked card is visible as it moves through hands and board; the marker is cosmetic and does not affect reveal scoring.",
    tags: ["visibility", "marked"],
    deal: { ...standardDeal, deck: "marked" },
    score: "high",
  },
  {
    id: "trickster-card",
    name: "Trickster Card",
    shortName: "Trick",
    summary: "One trickster card is shuffled in; whichever hand holds it finishes last.",
    detail: "The trickster marker overrides poker strength at reveal, dropping its hand below every non-trickster hand regardless of made-hand quality.",
    tags: ["identity", "marked"],
    deal: { ...standardDeal, deck: "trickster" },
    forceRankByMeta: { last: "trickster" },
    score: "high",
  },
  {
    id: "wild-edge",
    name: "Wild Edge",
    shortName: "Edge",
    summary: "Twos and aces are wild.",
    detail: "Both deck edges can substitute into the strongest available reveal identity.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["2", "A"] },
    score: "high",
  },
  {
    id: "twin-suits",
    name: "Twin Suits",
    shortName: "Twins",
    summary: "Hearts/diamonds and clubs/spades merge for flushes.",
    detail: "Red suits evaluate as one suit and black suits evaluate as one suit for showdown.",
    tags: ["identity", "suits"],
    deal: standardDeal,
    suitTransform: "color",
    score: "high",
  },
  {
    id: "card-counters",
    name: "Card Counters",
    shortName: "Counters",
    summary: "A public chip counts the cards still left in the deck.",
    detail: "The chip updates each street so the table can track how many cards remain undealt; scoring still uses the standard five-card board.",
    tags: ["info", "deck"],
    deal: standardDeal,
    infoFeatures: ["deck-count"],
    score: "high",
  },
  {
    id: "suit-census",
    name: "Suit Census",
    shortName: "Suit C",
    summary: "A public chip breaks down how many cards of each suit remain in the deck.",
    detail: "The suit counts refresh every street so the table can read suit pressure; scoring still uses the standard five-card board.",
    tags: ["info", "suits"],
    deal: standardDeal,
    infoFeatures: ["suit-census"],
    score: "high",
  },
  {
    id: "rank-census",
    name: "Rank Census",
    shortName: "Rank C",
    summary: "A public chip breaks down how many cards of each rank remain in the deck.",
    detail: "The rank counts refresh every street so the table can see which ranks are depleted; scoring still uses the standard five-card board.",
    tags: ["info", "ranks"],
    deal: standardDeal,
    infoFeatures: ["rank-census"],
    score: "high",
  },
  {
    id: "burn-reveal",
    name: "Burn Reveal",
    shortName: "Burn",
    summary: "The three burned cards are exposed to the whole table.",
    detail: "A public chip names the cards burned before the flop, turn, and river so the table knows what is not coming back; scoring is unchanged.",
    tags: ["info", "deck"],
    deal: standardDeal,
    infoFeatures: ["burn-reveal"],
    score: "high",
  },
  {
    id: "hint-card",
    name: "Hint Card",
    shortName: "Hint",
    summary: "At the turn, a public chip names one off-board card from the deck.",
    detail: "The hint appears only on the turn and previews a single card sitting in the deck, then vanishes for river and reveal scoring.",
    tags: ["info", "deck"],
    deal: standardDeal,
    infoFeatures: ["hint-card"],
    score: "high",
  },
  {
    id: "decoy",
    name: "Decoy",
    shortName: "Decoy",
    summary: "A public chip warns that one community card is a decoy without saying which.",
    detail: "Players know exactly one board card is non-scoring but never see which slot; reads must rely on inference and table talk.",
    tags: ["info", "board"],
    deal: standardDeal,
    infoFeatures: ["decoy"],
    score: "high",
  },
  {
    id: "lying-mirror",
    name: "Lying Mirror",
    shortName: "Mirror",
    summary: "At the flop, a public chip shows a fake three-card flop next to the real one.",
    detail: "Only the flop street displays the decoy three cards; turn, river, and reveal score against the genuine board with no chip in sight.",
    tags: ["info", "flop"],
    deal: standardDeal,
    infoFeatures: ["lying-mirror"],
    score: "high",
  },
  {
    id: "whisper-chain",
    name: "Whisper Chain",
    shortName: "Whisper",
    summary: "Each player gets a private hint about one neighbor's hand.",
    detail: "Every player sees one secret tip naming a neighbor and a fact about that neighbor's hole cards; the hint stays private to its recipient.",
    tags: ["info", "holes"],
    deal: { ...standardDeal, visibleHoleCards: { preflop: 1, flop: 1, turn: 1, river: 1, reveal: 2 } },
    infoFeatures: ["whisper-chain"],
    score: "high",
  },
  {
    id: "periscope",
    name: "Periscope",
    shortName: "Scope",
    summary: "At the river, each player privately sees one of a neighbor's hole cards.",
    detail: "Only on the river street does each player receive a private peek at a single hole card belonging to another hand; the chip is invisible to everyone else.",
    tags: ["info", "holes"],
    deal: { ...standardDeal, visibleHoleCards: { river: 1, reveal: 2 } },
    infoFeatures: ["periscope"],
    score: "high",
  },
  {
    id: "spotlight-rotation",
    name: "Spotlight Rotation",
    shortName: "Spotlight",
    summary: "A rotating hand is fully face-up to the table each street.",
    detail: "Every street, a different hand takes the spotlight and exposes both its hole cards while the other hands stay private until reveal.",
    tags: ["visibility", "holes"],
    deal: { ...standardDeal, visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 } },
    infoFeatures: ["spotlight"],
    score: "high",
  },
  {
    id: "half-lit-holes",
    name: "Half-Lit Holes",
    shortName: "Half-Lit",
    summary: "Each hand alternates which hole card is visible.",
    detail: "One hole card is public at every street, alternating between first and second before both are revealed.",
    tags: ["visibility", "holes"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 1, flop: 1, turn: 1, river: 1, reveal: 2 },
      visibleHoleCardIndexes: { preflop: [0], flop: [1], turn: [0], river: [1], reveal: [0, 1] },
    },
    infoFeatures: ["half-lit-holes"],
    score: "high",
  },
  {
    id: "mirror-hole",
    name: "Mirror Hole",
    shortName: "Mirror H",
    summary: "Each player privately sees one hole card from a neighbor's hand.",
    detail: "Every player receives a secret reflection of a single card belonging to another hand; the mirror stays private through reveal.",
    tags: ["info", "holes"],
    deal: standardDeal,
    infoFeatures: ["mirror-hole"],
    score: "high",
  },
  {
    id: "group-mind",
    name: "Group Mind",
    shortName: "Group",
    summary: "Everyone sees one shared hole card from every hand.",
    detail: "One public hole-card anchor per hand rotates as shared table knowledge across phases.",
    tags: ["visibility", "holes"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 1, flop: 1, turn: 1, river: 1, reveal: 2 },
      visibleHoleCardIndexes: { preflop: [0], flop: [1], turn: [0], river: [1], reveal: [0, 1] },
    },
    infoFeatures: ["group-mind"],
    score: "high",
  },
  {
    id: "tag-team",
    name: "Tag Team",
    shortName: "Tag",
    summary: "Each player privately sees a neighbor's full two-card hand.",
    detail: "Every player is tagged with another hand's complete hole cards as a private hint that persists from preflop through reveal.",
    tags: ["info", "holes"],
    deal: { ...standardDeal, visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 } },
    infoFeatures: ["tag-team"],
    score: "high",
  },
  {
    id: "smoke-hole",
    name: "Smoke Hole",
    shortName: "Smoke",
    summary: "Hole cards are suit-only until turn.",
    detail: "Every hand exposes only suit hints through flop, then full visible hole cards from turn onward.",
    tags: ["visibility", "suits"],
    deal: {
      ...standardDeal,
      visibleHoleCards: { preflop: 2, flop: 2, turn: 2, river: 2, reveal: 2 },
      visibleHoleCardDetail: { preflop: "suit", flop: "suit", turn: "full", river: "full", reveal: "full" },
    },
    infoFeatures: ["smoke-hole"],
    score: "high",
  },
  {
    id: "heat-map",
    name: "Heat Map",
    shortName: "Heat",
    summary: "The table is told whether the deck skews high or low.",
    detail: "A public chip compares how many high cards and low cards remain in the deck, refreshing every street.",
    tags: ["info", "deck"],
    deal: standardDeal,
    infoFeatures: ["heat-map"],
    score: "high",
  },
  {
    id: "suit-heat",
    name: "Suit Heat",
    shortName: "Suit Heat",
    summary: "The table is told which suit is over-represented.",
    detail: "A public chip names whichever suit has the most remaining cards in the deck, refreshing every street.",
    tags: ["info", "suits"],
    deal: standardDeal,
    infoFeatures: ["suit-heat"],
    score: "high",
  },
  {
    id: "sample-draw",
    name: "Sample Draw",
    shortName: "Sample",
    summary: "At the river, three cards from the leftover deck are exposed as a public sample.",
    detail: "The sample appears only on river street and previews three cards that never reach the board; scoring uses the normal five-card board.",
    tags: ["info", "deck"],
    deal: standardDeal,
    infoFeatures: ["sample-draw"],
    score: "high",
  },
  {
    id: "past-trace",
    name: "Past Trace",
    shortName: "Trace",
    summary: "A public chip echoes a fact about the previous hand into this one.",
    detail: "Between hands, a trace carries forward a single piece of public information from the prior reveal so the table starts each new hand with some memory.",
    tags: ["info", "memory"],
    deal: standardDeal,
    infoFeatures: ["past-trace"],
    score: "high",
  },
  {
    id: "tell",
    name: "Tell",
    shortName: "Tell",
    summary: "A public chip reveals one community card's true identity from the start.",
    detail: "From preflop onward, the chip names one community-card slot and its rank and suit, giving the table a guaranteed anchor.",
    tags: ["info", "board"],
    deal: standardDeal,
    infoFeatures: ["tell"],
    score: "high",
  },
  {
    id: "communal-glance",
    name: "Communal Glance",
    shortName: "Glance",
    summary: "The table sees one random hole-card slot.",
    detail: "One shared hole-card anchor per hand is public for the hand, preserving symmetric information.",
    tags: ["info", "holes"],
    deal: { ...standardDeal, visibleHoleCards: { preflop: 1, flop: 1, turn: 1, river: 1, reveal: 2 } },
    infoFeatures: ["communal-glance"],
    score: "high",
  },
  {
    id: "suit-whisper",
    name: "Suit Whisper",
    shortName: "S-Whisper",
    summary: "A public chip names one hand and a suit that hand does not hold.",
    detail: "The whisper narrows reads on a single hand by telling the table one suit it is missing, without ever exposing which cards it actually has.",
    tags: ["info", "suits"],
    deal: standardDeal,
    infoFeatures: ["suit-whisper"],
    score: "high",
  },
  {
    id: "rank-whisper",
    name: "Rank Whisper",
    shortName: "R-Whisper",
    summary: "A public chip names one hand and a rank that hand does not hold.",
    detail: "The whisper narrows reads on a single hand by telling the table one rank it is missing, without ever exposing which cards it actually has.",
    tags: ["info", "ranks"],
    deal: standardDeal,
    infoFeatures: ["rank-whisper"],
    score: "high",
  },
  {
    id: "phantom-card",
    name: "Phantom Card",
    shortName: "Phantom",
    summary: "A public chip names a rank that at least one hand is missing.",
    detail: "The phantom announces a single rank that is absent from at least one hand at the table, leaving the table to infer which hand it points at.",
    tags: ["info", "ranks"],
    deal: standardDeal,
    infoFeatures: ["phantom-card"],
    score: "high",
  },
  {
    id: "late-hand-reveal",
    name: "Late Hand Reveal",
    shortName: "Late Hand",
    summary: "At the river, every hand turns face up before the final ranking.",
    detail: "Hole cards stay private through preflop, flop, and turn, then flip publicly when the river arrives so the final read is fully open.",
    tags: ["visibility", "river"],
    deal: { ...standardDeal, visibleHoleCards: { river: 2, reveal: 2 } },
    infoFeatures: ["late-hand-reveal"],
    score: "high",
  },
  {
    id: "earthquake",
    name: "Earthquake",
    shortName: "Quake",
    summary: "At the turn, the community cards shake into a new order.",
    detail: "The board scrambles in place when the turn begins, keeping the same five cards but resetting any positional reads the table had built.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { turn: ["shuffleCommunity"] },
    infoFeatures: ["earthquake"],
    score: "high",
  },
  {
    id: "tornado",
    name: "Tornado",
    shortName: "Tornado",
    summary: "At the turn, every hand's hole cards rotate clockwise around the table.",
    detail: "When turn begins, each player loses their two cards to the next seat and inherits the previous seat's hand for the rest of the showdown.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateHoleCardsClockwise"] },
    infoFeatures: ["tornado"],
    score: "high",
  },
  {
    id: "lightning",
    name: "Lightning",
    shortName: "Lightning",
    summary: "At the river, every hand's first hole card jumps up one rank.",
    detail: "When the river arrives, the first kept card in every hand climbs a single rank, sharpening late made-hand pressure without touching the board.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["incrementFirstHolePerHand"] },
    infoFeatures: ["lightning"],
    score: "high",
  },
  {
    id: "flood",
    name: "Flood",
    shortName: "Flood",
    summary: "Every two, three, four, and five plays as a wild card at showdown.",
    detail: "The four lowest ranks all substitute into stronger identities at reveal, turning otherwise dead low cards into the building blocks of big made hands.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["2", "3", "4", "5"] },
    infoFeatures: ["flood"],
    score: "high",
  },
  {
    id: "drought",
    name: "Drought",
    shortName: "Drought",
    summary: "At the turn, every face card on the board is wiped away.",
    detail: "When the turn begins, jacks, queens, and kings disappear from the community cards and are replaced by fresh deck draws.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["removeFaceCards"] },
    infoFeatures: ["drought"],
    score: "high",
  },
  {
    id: "plague",
    name: "Plague",
    shortName: "Plague",
    summary: "At the turn, every seven on the board is wiped away.",
    detail: "When the turn begins, sevens disappear from the community cards and are replaced by fresh draws so the rank is rarely available at reveal.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["removeSevens"] },
    infoFeatures: ["plague"],
    score: "high",
  },
  {
    id: "solar-flare",
    name: "Solar Flare",
    shortName: "Flare",
    summary: "At the turn, every card on the table swaps to a new suit.",
    detail: "When the turn begins, suits reassign across hands and board on a fixed cycle, scrambling flush draws while ranks stay intact.",
    tags: ["event", "suits"],
    deal: standardDeal,
    phaseEffects: { turn: ["reassignAllSuits"] },
    infoFeatures: ["solar-flare"],
    score: "high",
  },
  {
    id: "meteor",
    name: "Meteor",
    shortName: "Meteor",
    summary: "At the turn, one visible community card is struck out and replaced.",
    detail: "When the turn begins, a single board card is swapped for a fresh draw from the deck, breaking one read while leaving the rest of the felt intact.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { turn: ["randomReplaceVisibleCommunity"] },
    infoFeatures: ["meteor"],
    score: "high",
  },
  {
    id: "mirror-universe",
    name: "Mirror Universe",
    shortName: "Mirror U",
    summary: "At the river, every rank flips across the deck's spine.",
    detail: "When river begins, every rank inverts so aces become twos, kings become threes, and so on across hands and board before reveal.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["invertAllRanks"] },
    infoFeatures: ["mirror-universe"],
    score: "high",
  },
  {
    id: "wildfire",
    name: "Wildfire",
    shortName: "Wildfire",
    summary: "When the river hits, the two ranks adjacent to it are wiped from the table.",
    detail: "On river street, both neighbor ranks of the river card burn out of every hand and the board, so each made hand has to rebuild around the gap.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["removeAdjacentToRiver"] },
    infoFeatures: ["wildfire"],
    score: "high",
  },
  {
    id: "avalanche",
    name: "Avalanche",
    shortName: "Avalanche",
    summary: "The board buries the table in seven community cards by river.",
    detail: "The flop shows three cards, the turn jumps to five, and the river piles on two more so reveal lands on a seven-card community board.",
    tags: ["event", "board"],
    deal: { ...standardDeal, communityCards: 7, visibleCommunityCards: { flop: 3, turn: 5, river: 7, reveal: 7 } },
    infoFeatures: ["avalanche"],
    score: "high",
  },
  {
    id: "storm-surge",
    name: "Storm Surge",
    shortName: "Surge",
    summary: "Each street, the oldest community card is swept off the board.",
    detail: "Flop drops the first board card, turn drops the next, and river drops another, so the board keeps shifting forward instead of accumulating.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { flop: ["stormSurge"], turn: ["stormSurge"], river: ["stormSurge"] },
    infoFeatures: ["storm-surge"],
    score: "high",
  },
  {
    id: "static",
    name: "Static",
    shortName: "Static",
    summary: "Each street, the community-card suits scramble while ranks stay fixed.",
    detail: "The board ranks lock in once dealt, but every new street reshuffles which suit each board card carries, breaking flush reads as the hand progresses.",
    tags: ["event", "suits"],
    deal: standardDeal,
    phaseEffects: { flop: ["scrambleCommunitySuits"], turn: ["scrambleCommunitySuits"], river: ["scrambleCommunitySuits"] },
    infoFeatures: ["static"],
    score: "high",
  },
  {
    id: "wormhole",
    name: "Wormhole",
    shortName: "Wormhole",
    summary: "At the river, the first two hands swap one hole card.",
    detail: "When river begins, the first hole card of seat one trades places with the first hole card of seat two, leaving the rest of the table untouched.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { river: ["swapFirstCardsFirstTwoHands"] },
    infoFeatures: ["wormhole"],
    score: "high",
  },
  {
    id: "black-hole",
    name: "Black Hole",
    shortName: "Black Hole",
    summary: "At the river, the most recent community card disappears into the void.",
    detail: "When river begins, the last card placed on the board vanishes and is not replaced, so the table ends the hand on a four-card community board.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { river: ["removeLastCommunity"] },
    infoFeatures: ["black-hole"],
    score: "high",
  },
  {
    id: "gravity-well",
    name: "Gravity Well",
    shortName: "Gravity",
    summary: "At the river, every hand's highest hole card climbs one rank.",
    detail: "When river begins, each hand's top card is pulled up a single rank, sharpening high-card and made-hand pressure across the final showdown.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["upgradeHighestHole"] },
    infoFeatures: ["gravity-well"],
    score: "high",
  },
  {
    id: "heat-wave",
    name: "Heat Wave",
    shortName: "Heat W",
    summary: "At turn, all face cards become aces.",
    detail: "Jacks, queens, and kings in hands and board convert to aces when turn begins.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["faceCardsToAces"] },
    infoFeatures: ["heat-wave"],
    score: "high",
  },
  {
    id: "cold-snap",
    name: "Cold Snap",
    shortName: "Cold",
    summary: "At turn, all face cards become twos.",
    detail: "Jacks, queens, and kings in hands and board convert to twos when turn begins.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["faceCardsToTwos"] },
    infoFeatures: ["cold-snap"],
    score: "high",
  },
  {
    id: "fog-bank",
    name: "Fog Bank",
    shortName: "Fog",
    summary: "Community cards show only their color until reveal.",
    detail: "From flop through river the board exposes color pressure only; reveal restores ranks and suits for scoring.",
    tags: ["visibility", "colors"],
    deal: { ...standardDeal, visibleCommunityCardDetail: { flop: "color", turn: "color", river: "color" } },
    infoFeatures: ["fog-bank"],
    score: "high",
  },
  {
    id: "rainstorm",
    name: "Rainstorm",
    shortName: "Rain",
    summary: "Every phase, one community card is replaced.",
    detail: "A fresh deck card replaces one visible community card at flop, turn, and river.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { flop: ["randomReplaceVisibleCommunity"], turn: ["randomReplaceVisibleCommunity"], river: ["randomReplaceVisibleCommunity"] },
    infoFeatures: ["rainstorm"],
    score: "high",
  },
  {
    id: "aurora",
    name: "Aurora",
    shortName: "Aurora",
    summary: "At river, suits swap within color pairs.",
    detail: "When river begins, suits reassign across hands and board on a fixed cycle, scrambling flush draws while ranks stay intact.",
    tags: ["event", "suits"],
    deal: standardDeal,
    phaseEffects: { river: ["reassignAllSuits"] },
    infoFeatures: ["aurora"],
    score: "high",
  },
  {
    id: "hurricane",
    name: "Hurricane",
    shortName: "Hurricane",
    summary: "At river, every player loses one hole card.",
    detail: "Each hand loses its final hole card when river begins.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { river: ["removeOneHolePerHand"] },
    infoFeatures: ["hurricane"],
    score: "high",
  },
  {
    id: "ice-age",
    name: "Ice Age",
    shortName: "Ice",
    summary: "Even ranks are frozen out of scoring.",
    detail: "Even-ranked cards are skipped by the reveal evaluator.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    excludedRanks: ["2", "4", "6", "8", "T", "Q"],
    infoFeatures: ["ice-age"],
    score: "high",
  },
  {
    id: "volcano",
    name: "Volcano",
    shortName: "Volcano",
    summary: "At river, one face-up card from each hand is destroyed.",
    detail: "The first hole card in each hand is destroyed when river begins.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { river: ["removeFirstHolePerHand"] },
    infoFeatures: ["volcano"],
    score: "high",
  },
  {
    id: "quantum-shuffle",
    name: "Quantum Shuffle",
    shortName: "Quantum",
    summary: "At turn, all hole cards are redistributed.",
    detail: "Hole cards are gathered, rotated, and redealt across the table when turn begins.",
    tags: ["event", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["shuffleAllHoleCards"] },
    infoFeatures: ["quantum-shuffle"],
    score: "high",
  },
  {
    id: "schrodingers-hole",
    name: "Schrodinger's Hole",
    shortName: "Schrodinger",
    summary: "Hole cards stay in superposition until reveal collapses them.",
    detail: "Every hand's private cards carry multiple possible identities through preflop, flop, turn, and river; reveal resolves each card to the strongest version for scoring.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "holes" },
    identityResolution: "bestPossible",
    infoFeatures: ["schrodingers-hole"],
    score: "high",
  },
  {
    id: "quantum-flop",
    name: "Quantum Flop",
    shortName: "Q Flop",
    summary: "Three possible flops exist at once.",
    detail: "Nine community cards form three flop boards; each hand scores against its best quantum board.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      communityCards: 9,
      boardLayout: {
        kind: "grid",
        slots: [
          { row: 0, col: 0, group: "flop-a" },
          { row: 0, col: 1, group: "flop-a" },
          { row: 0, col: 2, group: "flop-a" },
          { row: 1, col: 0, group: "flop-b" },
          { row: 1, col: 1, group: "flop-b" },
          { row: 1, col: 2, group: "flop-b" },
          { row: 2, col: 0, group: "flop-c" },
          { row: 2, col: 1, group: "flop-c" },
          { row: 2, col: 2, group: "flop-c" },
        ],
      },
      visibleCommunityCards: { flop: 9, turn: 9, river: 9, reveal: 9 },
      boards: { count: 3, cardsPerBoard: 3, scoring: "best" },
    },
    infoFeatures: ["quantum-flop"],
    score: "high",
  },
  {
    id: "probability-cloud",
    name: "Probability Cloud",
    shortName: "Cloud",
    summary: "Community cards carry unresolved alternate ranks.",
    detail: "Board cards have alternate identities before reveal; scoring resolves to the strongest possible version.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "board" },
    identityResolution: "bestPossible",
    infoFeatures: ["probability-cloud"],
    score: "high",
  },
  {
    id: "holographic-card",
    name: "Holographic Card",
    shortName: "Holo",
    summary: "Every community card carries multiple possible identities until reveal.",
    detail: "Each board card displays as uncertain through flop, turn, and river; reveal collapses every slot to whichever identity makes the strongest hand.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "board" },
    identityResolution: "bestPossible",
    infoFeatures: ["holographic-card"],
    score: "high",
  },
  {
    id: "schrodingers-board",
    name: "Schrodinger's Board",
    shortName: "S Board",
    summary: "The board exists in two possible versions.",
    detail: "Every community card carries a second possible identity; reveal scoring picks the strongest coherent version per hand.",
    tags: ["insanity", "board"],
    deal: { ...standardDeal, possibleIdentities: "board" },
    identityResolution: "bestPossible",
    infoFeatures: ["schrodingers-board"],
    score: "high",
  },
  {
    id: "card-multiverse",
    name: "Card Multiverse",
    shortName: "Multiverse",
    summary: "Four parallel five-card boards play out as alternate universes.",
    detail: "Twenty community cards form four separate five-card boards; each hand scores against its strongest universe at reveal.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      communityCards: 20,
      boardLayout: {
        kind: "grid",
        slots: [
          { row: 0, col: 0, group: "universe-a" },
          { row: 0, col: 1, group: "universe-a" },
          { row: 0, col: 2, group: "universe-a" },
          { row: 0, col: 3, group: "universe-a" },
          { row: 0, col: 4, group: "universe-a" },
          { row: 1, col: 0, group: "universe-b" },
          { row: 1, col: 1, group: "universe-b" },
          { row: 1, col: 2, group: "universe-b" },
          { row: 1, col: 3, group: "universe-b" },
          { row: 1, col: 4, group: "universe-b" },
          { row: 2, col: 0, group: "universe-c" },
          { row: 2, col: 1, group: "universe-c" },
          { row: 2, col: 2, group: "universe-c" },
          { row: 2, col: 3, group: "universe-c" },
          { row: 2, col: 4, group: "universe-c" },
          { row: 3, col: 0, group: "universe-d" },
          { row: 3, col: 1, group: "universe-d" },
          { row: 3, col: 2, group: "universe-d" },
          { row: 3, col: 3, group: "universe-d" },
          { row: 3, col: 4, group: "universe-d" },
        ],
      },
      visibleCommunityCards: { flop: 5, turn: 10, river: 20, reveal: 20 },
      boards: { count: 4, cardsPerBoard: 5, scoring: "best" },
    },
    infoFeatures: ["card-multiverse"],
    score: "high",
  },
  {
    id: "reality-tear",
    name: "Reality Tear",
    shortName: "Tear",
    summary: "One reality-torn card has multiple possible identities.",
    detail: "Cards can carry alternate identities and reveal scoring resolves the strongest possible version.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "holesAndBoard" },
    identityResolution: "bestPossible",
    infoFeatures: ["reality-tear"],
    score: "high",
  },
  {
    id: "identity-crisis",
    name: "Identity Crisis",
    shortName: "Crisis",
    summary: "At turn, a hole card and board card swap identities.",
    detail: "The first hand's first hole card swaps with the first community card when turn begins.",
    tags: ["insanity", "identity"],
    deal: standardDeal,
    phaseEffects: { turn: ["swapFirstHoleWithFirstCommunity"] },
    infoFeatures: ["identity-crisis"],
    score: "high",
  },
  {
    id: "drunken-display",
    name: "Drunken Display",
    shortName: "Drunken",
    summary: "Cards wobble between possible ranks until reveal sobers them up.",
    detail: "Hands and board carry alternate rank identities through preflop, flop, turn, and river; reveal collapses every card to whichever rank scores best.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "holesAndBoard" },
    identityResolution: "bestPossible",
    infoFeatures: ["drunken-display"],
    score: "high",
  },
  {
    id: "photographic-negative",
    name: "Photographic Negative",
    shortName: "Negative",
    summary: "Card colors invert visually after turn.",
    detail: "The board is color-only from turn through river, forcing players to reason through the negative display.",
    tags: ["visibility", "colors"],
    deal: { ...standardDeal, visibleCommunityCardDetail: { turn: "color", river: "color" } },
    infoFeatures: ["photographic-negative"],
    score: "high",
  },
  {
    id: "synesthesia",
    name: "Synesthesia",
    shortName: "Synesthesia",
    summary: "Each street shows the community cards through a different sensory filter.",
    detail: "Flop shows ranks only, turn shows suits only, and river shows colors only; the full board lands at reveal for scoring.",
    tags: ["visibility", "board"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetail: { flop: "rank", turn: "suit", river: "color" },
    },
    infoFeatures: ["synesthesia"],
    score: "high",
  },
  {
    id: "shapeshifter",
    name: "Shapeshifter",
    shortName: "Shifter",
    summary: "One community card changes identity each street.",
    detail: "The first community card upgrades one rank at flop, turn, and river.",
    tags: ["insanity", "identity"],
    deal: standardDeal,
    phaseEffects: { flop: ["incrementFirstCommunityRank"], turn: ["incrementFirstCommunityRank"], river: ["incrementFirstCommunityRank"] },
    infoFeatures: ["shapeshifter"],
    score: "high",
  },
  {
    id: "card-rebellion",
    name: "Card Rebellion",
    shortName: "Rebellion",
    summary: "At the turn, every hand rotates one seat clockwise around the table.",
    detail: "When turn begins, each player passes their two-card hand to the next seat and inherits the previous seat's hand for the rest of the showdown.",
    tags: ["insanity", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateHoleCardsClockwise"] },
    infoFeatures: ["card-rebellion"],
    score: "high",
  },
  {
    id: "card-theatre",
    name: "Card Theatre",
    shortName: "Theatre",
    summary: "Each street, a rotating hand is described in words instead of shown as cards.",
    detail: "A public clue narrates one hand's contents every phase, giving the table a flavorful read while the actual cards stay hidden until reveal.",
    tags: ["info", "holes"],
    deal: standardDeal,
    infoFeatures: ["card-theatre"],
    score: "high",
  },
  {
    id: "card-whisper-network",
    name: "Card Whisper Network",
    shortName: "Network",
    summary: "A public chip names one community card's true identity from the start.",
    detail: "From preflop onward, a network whisper exposes one community-card slot's rank and suit, giving every seat the same guaranteed anchor.",
    tags: ["info", "board"],
    deal: standardDeal,
    infoFeatures: ["card-whisper-network"],
    score: "high",
  },
  {
    id: "card-conscience",
    name: "Card Conscience",
    shortName: "Conscience",
    summary: "The deck announces a rank that has gone unused.",
    detail: "A public chip names the first rank that no one is holding and no community card shows, refreshing as the streets unfold.",
    tags: ["info", "ranks"],
    deal: standardDeal,
    infoFeatures: ["card-conscience"],
    score: "high",
  },
  {
    id: "card-festival",
    name: "Card Festival",
    shortName: "Festival",
    summary: "At the river, one community card boosts all the way up to an ace.",
    detail: "When river begins, the first board card becomes an ace, often shifting straight, set, and high-card reads going into reveal.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["festivalBoostFirstCommunity"] },
    infoFeatures: ["card-festival"],
    score: "high",
  },
  {
    id: "card-marriage",
    name: "Card Marriage",
    shortName: "Marriage",
    summary: "Cards are bonded into pairs that move and score together.",
    detail: "A public marker announces which cards are wedded; bonded cards travel as a unit and contribute to the same made-hand reads at reveal.",
    tags: ["identity", "marked"],
    deal: standardDeal,
    infoFeatures: ["card-marriage"],
    score: "high",
  },
  {
    id: "anti-memory",
    name: "Anti-Memory",
    shortName: "Anti-Memory",
    summary: "Seen cards fade while unseen cards surface.",
    detail: "The board starts fully visible, then progressively hides through river before reveal restores truth.",
    tags: ["insanity", "memory"],
    deal: { ...standardDeal, visibleCommunityCards: { preflop: 5, flop: 2, turn: 1, river: 0, reveal: 5 } },
    infoFeatures: ["anti-memory"],
    score: "high",
  },
  {
    id: "photographic-memory",
    name: "Photographic Memory",
    shortName: "Photo Mem",
    summary: "The flop disappears after you see it.",
    detail: "Flop is visible, then the board goes dark at turn and only partial river information returns.",
    tags: ["insanity", "memory"],
    deal: { ...standardDeal, visibleCommunityCards: { flop: 3, turn: 0, river: 2, reveal: 5 } },
    infoFeatures: ["photographic-memory"],
    score: "high",
  },
  {
    id: "memory-hole",
    name: "Memory Hole",
    shortName: "Mem Hole",
    summary: "At turn, one community card is forgotten.",
    detail: "One visible community card is replaced at turn and then masked through river.",
    tags: ["insanity", "memory"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetails: { turn: { 0: "hidden" }, river: { 0: "hidden" } },
    },
    phaseEffects: { turn: ["randomReplaceVisibleCommunity"] },
    infoFeatures: ["memory-hole"],
    score: "high",
  },
  {
    id: "time-echo",
    name: "Time Echo",
    shortName: "Echo",
    summary: "At river, the board returns to the flop.",
    detail: "The river phase truncates the board back to its first three community cards.",
    tags: ["insanity", "time"],
    deal: standardDeal,
    phaseEffects: { river: ["revertBoardToFlop"] },
    infoFeatures: ["time-echo"],
    score: "high",
  },
  {
    id: "reality-skip",
    name: "Reality Skip",
    shortName: "Skip",
    summary: "At the turn, the table glimpses a future street and snaps back unchanged.",
    detail: "A public skip notice fires at turn, previewing a possible future without altering the actual hands or board; everything resumes as if nothing happened.",
    tags: ["insanity", "time"],
    deal: standardDeal,
    infoFeatures: ["reality-skip"],
    score: "high",
  },
  {
    id: "reverse-universe",
    name: "Reverse Universe",
    shortName: "Reverse U",
    summary: "At river, table order and board order reverse.",
    detail: "The board and player order reverse when river begins while hand identities remain rankable.",
    tags: ["insanity", "time"],
    deal: standardDeal,
    phaseEffects: { river: ["reverseTableAndBoard"] },
    infoFeatures: ["reverse-universe"],
    score: "high",
  },
  {
    id: "card-singularity",
    name: "Card Singularity",
    shortName: "Singularity",
    summary: "At turn, each hand's cards collapse together.",
    detail: "The first two hole cards in each hand merge into one averaged-rank card when turn begins.",
    tags: ["insanity", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["singularityAverageFirstTwoHoles"] },
    infoFeatures: ["card-singularity"],
    score: "high",
  },
  {
    id: "glitch-wars",
    name: "Glitch Wars",
    shortName: "Glitch Wars",
    summary: "At turn, board cards fight over suit identity.",
    detail: "The first community card absorbs the second community card's suit when turn begins.",
    tags: ["insanity", "suits"],
    deal: standardDeal,
    phaseEffects: { turn: ["firstCommunityAbsorbsSecondSuit"] },
    infoFeatures: ["glitch-wars"],
    score: "high",
  },
  {
    id: "card-convergence",
    name: "Card Convergence",
    shortName: "Converge",
    summary: "At river, one rank converges into aces.",
    detail: "When river begins, every seven in hands and on the board converges into an ace before reveal scoring.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["convergeSevensToAces"] },
    infoFeatures: ["card-convergence"],
    score: "high",
  },
  {
    id: "card-halo",
    name: "Card Halo",
    shortName: "Halo",
    summary: "Neighboring ranks gain a pair aura.",
    detail: "Adjacent ranks can create a synthetic pair during showdown.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    syntheticPair: "adjacent",
    infoFeatures: ["card-halo"],
    score: "high",
  },
  {
    id: "card-vortex",
    name: "Card Vortex",
    shortName: "Vortex",
    summary: "At turn, ranks rotate around the table.",
    detail: "Hole-card ranks rotate across table order while suits stay in their slots.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateHoleRanksAcrossHands"] },
    infoFeatures: ["card-vortex"],
    score: "high",
  },
  {
    id: "card-eclipse-total",
    name: "Card Eclipse Total",
    shortName: "Eclipse T",
    summary: "At river, the highest rank in play vanishes.",
    detail: "Every card of the current highest rank is removed from hands and board at river.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["removeHighestRankInPlay"] },
    infoFeatures: ["card-eclipse-total"],
    score: "high",
  },
  {
    id: "card-plague-spread",
    name: "Card Plague Spread",
    shortName: "Spread",
    summary: "A plague rank infects more cards each phase.",
    detail: "One additional card converts to seven at flop, turn, and river.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { flop: ["spreadPlagueToFirstCard"], turn: ["spreadPlagueToFirstCard"], river: ["spreadPlagueToFirstCard"] },
    infoFeatures: ["card-plague-spread"],
    score: "high",
  },
  {
    id: "card-diaspora",
    name: "Card Diaspora",
    shortName: "Diaspora",
    summary: "At turn, every hand gives one card away.",
    detail: "The first hole card in each hand rotates to the next hand when turn begins.",
    tags: ["insanity", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateFirstHoleCardsClockwise"] },
    infoFeatures: ["card-diaspora"],
    score: "high",
  },
  {
    id: "card-soup",
    name: "Card Soup",
    shortName: "Soup",
    summary: "At turn, holes and burn pile mix together.",
    detail: "When turn begins, every hand's hole cards mix with the burn pile and are dealt back out across the table.",
    tags: ["insanity", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["mixHolesWithBurn"] },
    infoFeatures: ["card-soup"],
    score: "high",
  },
  {
    id: "card-madness",
    name: "Card Madness",
    shortName: "Madness",
    summary: "At turn, every card swaps places.",
    detail: "All hole and community cards rotate one position through a single shared stream.",
    tags: ["insanity", "holes"],
    deal: standardDeal,
    phaseEffects: { turn: ["rotateAllCardPositions"] },
    infoFeatures: ["card-madness"],
    score: "high",
  },
  {
    id: "card-tide",
    name: "Card Tide",
    shortName: "Tide",
    summary: "Every street, all ranks drift upward.",
    detail: "All ranks shift +1 at flop, turn, and river.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { flop: ["incrementAllRanks"], turn: ["incrementAllRanks"], river: ["incrementAllRanks"] },
    infoFeatures: ["card-tide"],
    score: "high",
  },
  {
    id: "card-drift",
    name: "Card Drift",
    shortName: "Drift",
    summary: "Every street, private cards drift upward.",
    detail: "Hole-card ranks shift +1 at flop, turn, and river.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { flop: ["incrementAllHoleRanks"], turn: ["incrementAllHoleRanks"], river: ["incrementAllHoleRanks"] },
    infoFeatures: ["card-drift"],
    score: "high",
  },
  {
    id: "recursive-board",
    name: "Recursive Board",
    shortName: "Recursive",
    summary: "At turn, the board duplicates itself.",
    detail: "The board recursively mirrors into ten displayed cards at turn.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "mirror" },
      visibleCommunityCards: { flop: 3, turn: 10, river: 10, reveal: 10 },
      scoreCommunityCards: 5,
    },
    phaseEffects: { turn: ["mirrorCommunity"] },
    infoFeatures: ["recursive-board"],
    score: "high",
  },
  {
    id: "mirror-hand",
    name: "Mirror Hand",
    shortName: "M Hand",
    summary: "Every hand has a shadow inversion.",
    detail: "Hole cards carry alternate identities so each hand can resolve through its mirrored possibility.",
    tags: ["insanity", "identity"],
    deal: { ...standardDeal, possibleIdentities: "holes" },
    identityResolution: "bestPossible",
    infoFeatures: ["mirror-hand"],
    score: "high",
  },
  {
    id: "twin-universes",
    name: "Twin Universes",
    shortName: "Twin U",
    summary: "Two board universes play out side-by-side.",
    detail: "Ten community cards form two five-card boards; each hand scores against its better universe.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      communityCards: 10,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "vault" },
      visibleCommunityCards: { flop: 5, turn: 10, river: 10, reveal: 10 },
      boards: { count: 2, cardsPerBoard: 5, scoring: "best" },
    },
    infoFeatures: ["twin-universes"],
    score: "high",
  },
  {
    id: "mirror-world",
    name: "Mirror World",
    shortName: "M World",
    summary: "Two realities are visible before reveal picks a ranking.",
    detail: "Two five-card boards are shown, with hands scored against their better reality.",
    tags: ["insanity", "board"],
    deal: {
      ...standardDeal,
      communityCards: 10,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "mirror" },
      visibleCommunityCards: { flop: 5, turn: 5, river: 10, reveal: 10 },
      boards: { count: 2, cardsPerBoard: 5, scoring: "best" },
    },
    infoFeatures: ["mirror-world"],
    score: "high",
  },
  {
    id: "card-constellation",
    name: "Card Constellation",
    shortName: "Constellation",
    summary: "Sevens form a constellation across the table and play as wild cards.",
    detail: "Every seven, in hands or on the board, can substitute for whichever rank or suit completes the strongest reveal hand.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["7"] },
    infoFeatures: ["card-constellation"],
    score: "high",
  },
  {
    id: "card-karma",
    name: "Card Karma",
    shortName: "Karma",
    summary: "A card from the previous hand echoes into this one as a karmic memory.",
    detail: "Between hands, a public karma notice carries forward one card from the prior reveal so the new hand starts with shared memory of what came before.",
    tags: ["info", "memory"],
    deal: standardDeal,
    infoFeatures: ["card-karma"],
    score: "high",
  },
  {
    id: "card-resurrection",
    name: "Card Resurrection",
    shortName: "Resurrect",
    summary: "Discarded cards reappear as community cards.",
    detail: "Each hand is dealt three, keeps two automatically, and the discarded cards join the board at reveal.",
    tags: ["insanity", "discards"],
    deal: { ...standardDeal, holeCards: 3, keepCards: 2, discardedCardsToCommunity: true, visibleCommunityCards: { reveal: 22 } },
    infoFeatures: ["card-resurrection"],
    score: "high",
  },
  {
    id: "card-memorial",
    name: "Card Memorial",
    shortName: "Memorial",
    summary: "A memorial sixth board card appears at reveal as a tribute to discards.",
    detail: "The board grows from three to six community cards across streets, and the extra card joins the felt at reveal as memorial information only.",
    tags: ["insanity", "memory"],
    deal: { ...standardDeal, communityCards: 6, visibleCommunityCards: { flop: 3, turn: 4, river: 5, reveal: 6 }, scoreCommunityCards: 5 },
    infoFeatures: ["card-memorial"],
    score: "high",
  },
  {
    id: "hex-card",
    name: "Hex Card",
    shortName: "Hex",
    summary: "One hex card is shuffled in; whichever hand holds it finishes last.",
    detail: "The hex marker overrides poker strength at reveal, dropping the hexed hand below every non-hexed hand regardless of made-hand quality.",
    tags: ["identity", "marked"],
    deal: { ...standardDeal, deck: "cursed" },
    forceRankByMeta: { last: "cursed" },
    infoFeatures: ["hex-card"],
    score: "high",
  },
  {
    id: "blessed-card-absolute",
    name: "Blessed Card Absolute",
    shortName: "Bless Abs",
    summary: "One absolute-blessed card is shuffled in; whichever hand holds it finishes first.",
    detail: "The blessing overrides poker strength at reveal, lifting its hand above every other hand regardless of made-hand quality.",
    tags: ["identity", "marked"],
    deal: { ...standardDeal, deck: "blessed" },
    forceRankByMeta: { first: "blessed" },
    infoFeatures: ["blessed-card-absolute"],
    score: "high",
  },
  {
    id: "doomsday-card",
    name: "Doomsday Card",
    shortName: "Doomsday",
    summary: "At the river, the doomsday card flips every rank in play upside down.",
    detail: "When river begins, all ranks across hands and board invert so aces become twos, kings become threes, and so on before reveal.",
    tags: ["event", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["invertAllRanks"] },
    infoFeatures: ["doomsday-card"],
    score: "high",
  },
  {
    id: "card-cipher",
    name: "Card Cipher",
    shortName: "Cipher",
    summary: "At river, values are encoded through the river card.",
    detail: "Every rank shifts by the river card's rank index when river begins.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { river: ["cipherRanksWithRiver"] },
    infoFeatures: ["card-cipher"],
    score: "high",
  },
  {
    id: "card-decoy",
    name: "Card Decoy",
    shortName: "Decoy",
    summary: "Six community cards are dealt; one is a decoy that does not score, but the chip does not say which.",
    detail: "The felt grows to a six-card row across flop/turn/river and a chip warns that one community card does not score, but the decoy is not marked on the felt — players cannot identify it without inference.",
    tags: ["board", "decoy"],
    deal: { ...standardDeal, communityCards: 6, visibleCommunityCards: { flop: 4, turn: 5, river: 6, reveal: 6 }, scoreCommunityCards: 5 },
    infoFeatures: ["card-decoy"],
    score: "high",
  },
  {
    id: "card-static",
    name: "Card Static",
    shortName: "C Static",
    summary: "Cards flicker into new ranks as the hand progresses.",
    detail: "The first hole card and first board card shift upward each street.",
    tags: ["insanity", "ranks"],
    deal: standardDeal,
    phaseEffects: { flop: ["staticFlickerFirstCards"], turn: ["staticFlickerFirstCards"], river: ["staticFlickerFirstCards"] },
    infoFeatures: ["card-static"],
    score: "high",
  },
  {
    id: "cell-division",
    name: "Cell Division",
    shortName: "Division",
    summary: "At reveal, every hand splits in two.",
    detail: "Each two-card hand divides into two one-card hands at reveal, and the ranking expands to include the split hands.",
    tags: ["insanity", "holes"],
    deal: standardDeal,
    phaseEffects: { reveal: ["splitHandsAtReveal"] },
    infoFeatures: ["cell-division"],
    score: "high",
  },
  {
    id: "card-schism",
    name: "Card Schism",
    shortName: "Schism",
    summary: "At the turn, the remaining deck splits and only the high half stays in play.",
    detail: "When turn begins, every later draw — for board replacements or other effects — comes only from the deck's high ranks.",
    tags: ["event", "deck"],
    deal: standardDeal,
    phaseEffects: { turn: ["schismDeckHighOnly"] },
    infoFeatures: ["card-schism"],
    score: "high",
  },
  {
    id: "card-pendulum",
    name: "Card Pendulum",
    shortName: "Pendulum",
    summary: "Every seven plays as a wild card at showdown.",
    detail: "The pendulum locks sevens as the wild rank for the hand, letting every seven substitute for whichever rank or suit improves the made hand at reveal.",
    tags: ["wild", "ranks"],
    deal: standardDeal,
    wildCards: { ranks: ["7"] },
    infoFeatures: ["card-pendulum"],
    score: "high",
  },
  {
    id: "card-pinball",
    name: "Card Pinball",
    shortName: "Pinball",
    summary: "A community card bounces into a hole slot.",
    detail: "The first community card swaps with the first hole card at flop, turn, and river.",
    tags: ["insanity", "board"],
    deal: standardDeal,
    phaseEffects: { flop: ["swapFirstHoleWithFirstCommunity"], turn: ["swapFirstHoleWithFirstCommunity"], river: ["swapFirstHoleWithFirstCommunity"] },
    infoFeatures: ["card-pinball"],
    score: "high",
  },
  {
    id: "card-inheritance",
    name: "Card Inheritance",
    shortName: "Inherit",
    summary: "Discards inherit from the board before disappearing.",
    detail: "Hands are dealt three and keep two automatically while a public inheritance hint tracks the disappearing discard rule.",
    tags: ["insanity", "discards"],
    deal: { ...standardDeal, holeCards: 3, keepCards: 2 },
    infoFeatures: ["card-inheritance"],
    score: "high",
  },
  {
    id: "doppelganger-deck",
    name: "Doppelganger Deck",
    shortName: "Doppel",
    summary: "Every card has a hidden twin somewhere else.",
    detail: "The deck is doubled so duplicate identities can appear across hands and board.",
    tags: ["deck", "duplicates"],
    deal: { ...standardDeal, deck: "double" },
    infoFeatures: ["doppelganger-deck"],
    score: "high",
  },
  {
    id: "telepathic-river",
    name: "Telepathic River",
    shortName: "Telepathy",
    summary: "At the river, the table picks up a vague hint about a neighboring hand.",
    detail: "On river street, a public broadcast carries a fuzzy clue about a nearby hand's cards while the underlying scoring stays unchanged.",
    tags: ["info", "river"],
    deal: standardDeal,
    infoFeatures: ["telepathic-river"],
    score: "high",
  },
  {
    id: "card-whisper",
    name: "Card Whisper",
    shortName: "Whisper",
    summary: "At the river, a public whisper names one community card's true identity.",
    detail: "The chip stays silent through preflop, flop, and turn, then reveals one board slot's rank and suit on river street as a late-stage anchor.",
    tags: ["info", "river"],
    deal: standardDeal,
    infoFeatures: ["card-whisper"],
    score: "high",
  },
  {
    id: "card-lunar",
    name: "Card Lunar",
    shortName: "Lunar",
    summary: "Hearts wax full and play as wild cards at showdown.",
    detail: "Every heart in a hand or on the board can stand in for whichever rank or suit completes the strongest reveal hand.",
    tags: ["insanity", "suits"],
    deal: standardDeal,
    wildCards: { suits: ["H"] },
    infoFeatures: ["card-lunar"],
    score: "high",
  },
  {
    id: "pandemonium",
    name: "Pandemonium",
    shortName: "Pandemonium",
    summary: "A different chaos effect fires every street, with cards in superposition all the way through.",
    detail: "Flop bumps every rank up, turn rotates hole-card ranks across the table, and river inverts ranks; reveal collapses every superposed card to whichever identity scores best.",
    tags: ["insanity", "ranks"],
    deal: { ...standardDeal, possibleIdentities: "holesAndBoard" },
    identityResolution: "bestPossible",
    phaseEffects: { flop: ["incrementAllRanks"], turn: ["rotateHoleRanksAcrossHands"], river: ["invertAllRanks"] },
    infoFeatures: ["pandemonium"],
    score: "high",
  },
  {
    id: "lowball",
    name: "Lowball Ding",
    shortName: "Lowball",
    summary: "The worst poker hand wins the top slot.",
    detail: "Ranking instincts invert: weak high-card hands become the hands to protect.",
    tags: ["objective", "lowball"],
    deal: standardDeal,
    score: "lowball",
  },
  {
    id: "omaha-luxe",
    name: "Omaha Luxe",
    shortName: "Omaha",
    summary: "Four private cards per hand, best five-card poker hand wins.",
    detail: "More private information creates bigger late-street reversals and tougher negotiation.",
    tags: ["big-hands", "dense"],
    deal: { ...standardDeal, holeCards: 4 },
    score: "high",
  },
  {
    id: "pent",
    name: "Pent",
    shortName: "Pent",
    summary: "Five private cards per hand make every hand information-dense.",
    detail: "Each hand starts with five hole cards, then still uses the shared board to find its best five-card poker hand.",
    tags: ["big-hands", "dense"],
    deal: { ...standardDeal, holeCards: 5 },
    score: "high",
  },
  {
    id: "solitaire-suite",
    name: "Solitaire Suite",
    shortName: "Solitaire",
    summary: "Seven private cards per hand; the board is mostly a side dish.",
    detail: "Every hand gets seven hole cards and scores the best five-card poker hand available with the board.",
    tags: ["big-hands", "solo"],
    deal: { ...standardDeal, holeCards: 7 },
    score: "high",
  },
  {
    id: "players-choice",
    name: "Player's Choice",
    shortName: "Choice",
    summary: "Every hand is dealt three cards; the owner keeps any two before ranking starts.",
    detail: "A deal-choice phase lets each player sculpt their starting hands, then the game continues as classic Ding.",
    tags: ["choice", "deal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 3, keepCards: 2, selectionPhase: true },
    },
    score: "high",
  },
  {
    id: "pick-2-of-5",
    name: "Pick 2 of 5",
    shortName: "Pick 2",
    summary: "Every hand is dealt five cards; the owner keeps any two before ranking starts.",
    detail: "A deeper deal-choice phase gives each player five private candidates and asks them to sculpt a two-card start.",
    tags: ["choice", "deal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 5, keepCards: 2, selectionPhase: true },
    },
    score: "high",
  },
  {
    id: "pick-3-of-7",
    name: "Pick 3 of 7",
    shortName: "Pick 3",
    summary: "Every hand is dealt seven cards; the owner keeps any three before ranking starts.",
    detail: "A heavy deal-choice phase gives each player seven private candidates and asks them to sculpt a three-card start.",
    tags: ["choice", "deal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 7, keepCards: 3, selectionPhase: true },
    },
    score: "high",
  },
  {
    id: "mulligan",
    name: "Mulligan",
    shortName: "Mulligan",
    summary: "Every hand may refuse its first two cards once and redraw before ranking starts.",
    detail: "A deal-choice phase lets each hand either lock its original two-card start or spend a one-time full redraw.",
    tags: ["choice", "redeal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 2, keepCards: 2, selectionPhase: true, mulligan: true },
    },
    score: "high",
  },
  {
    id: "trade-up",
    name: "Trade-Up",
    shortName: "Trade-Up",
    summary: "At the deal, each hand passes one selected card to the left neighbor.",
    detail: "Every owner chooses one hole card to trade away. Cards move simultaneously around the table before preflop ranking starts.",
    tags: ["choice", "trade"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 2, keepCards: 1, selectionPhase: true, tradeUp: true },
    },
    score: "high",
  },
  {
    id: "inheritance",
    name: "Inheritance",
    shortName: "Inherit",
    summary: "Keep one hole card; your second card comes from the right neighbor's discard.",
    detail: "Every owner chooses one card to keep. The other card is discarded left, so each final hand combines one kept card with the right neighbor's discarded card.",
    tags: ["choice", "deal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 2, keepCards: 1, selectionPhase: true, inheritance: true },
    },
    score: "high",
  },
  {
    id: "look-then-choose",
    name: "Look-Then-Choose",
    shortName: "Look",
    summary: "Peek three deal cards and keep any two before ranking starts.",
    detail: "Each hand sees three private candidates from the deck, chooses two to keep, and starts preflop with that sculpted two-card hand.",
    tags: ["choice", "deal"],
    deal: {
      ...standardDeal,
      dealChoice: { dealtCards: 3, keepCards: 2, selectionPhase: true },
    },
    score: "high",
  },
  {
    id: "echo",
    name: "Echo",
    shortName: "Echo",
    summary: "Both hole cards in every hand share a rank.",
    detail: "Every hand starts as a pocket pair, creating dense rank collisions and sharper kicker races through the board.",
    tags: ["constrained", "pairs"],
    deal: { ...standardDeal, constraint: "pocketPair" },
    score: "high",
  },
  {
    id: "mirror-match",
    name: "Mirror Match",
    shortName: "Mirror",
    summary: "Every hand shares the same first hole card.",
    detail: "A single mirrored anchor card appears in every hand, so the second hole card and board texture decide the spread.",
    tags: ["constrained", "mirror"],
    deal: { ...standardDeal, constraint: "sharedFirstCard" },
    score: "high",
  },
  {
    id: "rainbow-hole",
    name: "Rainbow Hole",
    shortName: "Rainbow",
    summary: "Hole cards in every hand are guaranteed different suits.",
    detail: "Every hand starts with two suits represented, reducing suited-hole certainty while keeping classic high-hand scoring.",
    tags: ["constrained", "suits"],
    deal: { ...standardDeal, constraint: "differentSuits" },
    score: "high",
  },
  {
    id: "suited-hole",
    name: "Suited Hole",
    shortName: "Suited",
    summary: "Hole cards in every hand are guaranteed the same suit.",
    detail: "Every hand starts suited, making flush paths more visible without changing classic high-hand scoring.",
    tags: ["constrained", "suits"],
    deal: { ...standardDeal, constraint: "sameSuit" },
    score: "high",
  },
  {
    id: "connected-hole",
    name: "Connected Hole",
    shortName: "Connected",
    summary: "Hole cards in every hand are guaranteed adjacent ranks.",
    detail: "Every hand starts with neighboring ranks, creating visible straight paths while keeping classic high-hand scoring.",
    tags: ["constrained", "ranks"],
    deal: { ...standardDeal, constraint: "connectedRanks" },
    score: "high",
  },
  {
    id: "gapped-hole",
    name: "Gapped Hole",
    shortName: "Gapped",
    summary: "Hole cards in every hand are guaranteed two ranks apart.",
    detail: "Every hand starts with a one-rank gap between its cards, creating less direct straight texture than Connected Hole.",
    tags: ["constrained", "ranks"],
    deal: { ...standardDeal, constraint: "gappedRanks" },
    score: "high",
  },
  {
    id: "polar-hole",
    name: "Polar Hole",
    shortName: "Polar",
    summary: "Every hand starts with one high card and one low card.",
    detail: "Each two-card hand is split between the 8-A high band and the 2-7 low band, creating visible kicker asymmetry.",
    tags: ["constrained", "ranks"],
    deal: { ...standardDeal, constraint: "polarRanks" },
    score: "high",
  },
  {
    id: "twin-spark",
    name: "Twin Spark",
    shortName: "Twin",
    summary: "Both hole cards in every hand come from the low ranks.",
    detail: "Every hand starts with two cards from 2 through 7, compressing early strength and making board improvement matter more.",
    tags: ["constrained", "ranks"],
    deal: { ...standardDeal, constraint: "lowRanks" },
    score: "high",
  },
  {
    id: "royal-spark",
    name: "Royal Spark",
    shortName: "Royal",
    summary: "Both hole cards in every hand come from the high ranks.",
    detail: "Every hand starts with two cards from 8 through Ace, making preflop strength dense and board kickers sharper.",
    tags: ["constrained", "ranks"],
    deal: { ...standardDeal, constraint: "highRanks" },
    score: "high",
  },
  {
    id: "triad",
    name: "Triad",
    shortName: "Triad",
    summary: "Three private cards per hand, best five-card poker hand wins.",
    detail: "A lighter multi-card mode with enough extra texture to make rankings less obvious.",
    tags: ["big-hands", "dense"],
    deal: { ...standardDeal, holeCards: 3 },
    score: "high",
  },
  {
    id: "single-spark",
    name: "Single Spark",
    shortName: "Spark",
    summary: "Each hand gets one private card instead of two.",
    detail: "Tiny private edges make public-board reading and player confidence matter more.",
    tags: ["big-hands", "solo"],
    deal: { ...standardDeal, holeCards: 1 },
    score: "high",
  },
  {
    id: "double-river",
    name: "Double River",
    shortName: "2 River",
    summary: "The river reveals two final community cards.",
    detail: "Six-card boards create dramatic final re-sorts without changing the core loop.",
    tags: ["board", "river"],
    deal: {
      holeCards: 2,
      communityCards: 6,
      visibleCommunityCards: { ...baseVisibleCommunity, river: 6, reveal: 6 },
    },
    score: "high",
  },
  {
    id: "big-sky",
    name: "Big Sky",
    shortName: "Big Sky",
    summary: "A seven-card board gives every hand more ways to connect.",
    detail: "The board grows to four on the flop, five on the turn, and seven on the river.",
    tags: ["board", "community"],
    deal: {
      holeCards: 2,
      communityCards: 7,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 4, turn: 5, river: 7, reveal: 7 },
    },
    score: "high",
  },
  {
    id: "tiny-board",
    name: "Tiny Board",
    shortName: "Tiny",
    summary: "Only three community cards are dealt.",
    detail: "The flop is the whole board, so private cards matter longer and there is no late board rescue.",
    tags: ["board", "community"],
    deal: {
      holeCards: 2,
      communityCards: 3,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 3, river: 3, reveal: 3 },
    },
    score: "high",
  },
  {
    id: "mini-board",
    name: "Mini Board",
    shortName: "Mini",
    summary: "Four community cards are dealt.",
    detail: "The board gets a normal flop and one turn card, then stays fixed through river.",
    tags: ["board", "community"],
    deal: {
      holeCards: 2,
      communityCards: 4,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 4, reveal: 4 },
    },
    score: "high",
  },
  {
    id: "behemoth",
    name: "Behemoth",
    shortName: "Behemoth",
    summary: "Nine community cards are dealt; best five-card poker hand wins.",
    detail: "The river dumps the rest of a huge board, creating a crowded final comparison across eleven available cards.",
    tags: ["board", "community"],
    deal: {
      holeCards: 2,
      communityCards: 9,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 9, reveal: 9 },
    },
    score: "high",
  },
  {
    id: "two-boards",
    name: "Two Boards",
    shortName: "2 Boards",
    summary: "Two parallel boards are dealt; every hand scores against its better board.",
    detail: "Each street reveals cards on both boards, and showdown evaluates every hand on both boards before keeping its strongest result.",
    tags: ["board", "multi-board"],
    deal: {
      holeCards: 2,
      communityCards: 10,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "vault" },
      boards: { count: 2, cardsPerBoard: 5, scoring: "best" },
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 6, turn: 8, river: 10, reveal: 10 },
    },
    score: "high",
  },
  {
    id: "split-board",
    name: "Split Board",
    shortName: "Split",
    summary: "Six community cards form two three-card halves; every hand scores on its better half.",
    detail: "The whole split board lands together, but each hand only combines with one side at showdown.",
    tags: ["board", "multi-board"],
    deal: {
      holeCards: 2,
      communityCards: 6,
      boardLayout: { kind: "dual", primary: 3, secondary: 3, secondaryRole: "vault" },
      boards: { count: 2, cardsPerBoard: 3, scoring: "best" },
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 6, turn: 6, river: 6, reveal: 6 },
    },
    score: "high",
  },
  {
    id: "tower",
    name: "Tower",
    shortName: "Tower",
    summary: "A five-card stack shows only its top three cards until river.",
    detail: "The table reads a stable three-card board through turn, then the hidden bottom of the stack appears at river.",
    tags: ["visibility", "board"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 3, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "cross",
    name: "Cross",
    shortName: "Cross",
    summary: "Five community cards form a cross; every hand scores on its better line.",
    detail: "The center card belongs to both the row and the column, so hands can connect along either axis.",
    tags: ["board", "topology"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      boardLayout: { kind: "grid", slots: [
        { row: 1, col: 0 },
        { row: 0, col: 1 },
        { row: 1, col: 1, group: "center" },
        { row: 2, col: 1 },
        { row: 1, col: 2 },
      ] },
      boards: {
        cardIndexes: [[0, 2, 4], [1, 2, 3]],
        scoring: "best",
      },
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "l-board",
    name: "L-Board",
    shortName: "L-Board",
    summary: "Seven community cards form an L; every hand scores on its best five-card path.",
    detail: "The L is scored as overlapping five-card paths along the bend, creating several possible board lanes.",
    tags: ["board", "topology"],
    deal: {
      holeCards: 2,
      communityCards: 7,
      boardLayout: { kind: "L", arm: 5, stem: 3 },
      boards: {
        cardIndexes: [[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6]],
        scoring: "best",
      },
      visibleCommunityIndexes: {
        lobby: [],
        preflop: [],
        flop: [0, 1, 2, 5, 6],
        turn: [0, 1, 2, 3, 5, 6],
        river: [0, 1, 2, 3, 4, 5, 6],
        reveal: [0, 1, 2, 3, 4, 5, 6],
      },
    },
    score: "high",
  },
  {
    id: "flash-flop",
    name: "Flash Flop",
    shortName: "Flash",
    summary: "The flop is visible before anyone ranks a hand.",
    detail: "Players start with real board context, so early rankings are less random.",
    tags: ["tempo", "flop"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { ...baseVisibleCommunity, preflop: 3 },
    },
    score: "high",
  },
  {
    id: "flash-river",
    name: "Flash River",
    shortName: "Flash R",
    summary: "The full board is visible before anyone ranks a hand.",
    detail: "All five community cards are public at preflop, turning the whole hand into immediate table-reading.",
    tags: ["visibility", "board"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { ...baseVisibleCommunity, preflop: 5, flop: 5, turn: 5, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "blackout",
    name: "Blackout",
    shortName: "Blackout",
    summary: "No community cards are shown until the river.",
    detail: "The first three streets are pure private-hand debate, then the board lands all at once.",
    tags: ["tempo", "river"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 0, turn: 0, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "slow-burn",
    name: "Slow Burn",
    shortName: "Slow",
    summary: "The board arrives one card, then three, then five.",
    detail: "A narrow flop makes early confidence brittle and keeps trades alive longer.",
    tags: ["tempo", "board"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 1, turn: 3, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "turnpike",
    name: "Turnpike",
    shortName: "Turnpike",
    summary: "Four community cards hit on the flop, then the game pauses before the river.",
    detail: "Most of the board appears early, making the final card a sharper negotiation point.",
    tags: ["tempo", "board"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 4, turn: 4, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "crawl",
    name: "Crawl",
    shortName: "Crawl",
    summary: "The board crawls out slowly before completing at river.",
    detail: "One card is visible preflop, then the board inches forward before the final two cards arrive at river.",
    tags: ["tempo", "board"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 1, flop: 2, turn: 3, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "eclipse-suit",
    name: "Eclipse Suit",
    shortName: "Eclipse S",
    summary: "Community cards show suits only until reveal.",
    detail: "The board's suit texture is visible, but ranks stay hidden until the final reveal.",
    tags: ["visibility", "suits"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetail: { preflop: "suit", flop: "suit", turn: "suit", river: "suit" },
    },
    score: "high",
  },
  {
    id: "eclipse-rank",
    name: "Eclipse Rank",
    shortName: "Eclipse R",
    summary: "Community cards show ranks only until reveal.",
    detail: "The board's rank structure is visible, but suits stay hidden until the final reveal.",
    tags: ["visibility", "ranks"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetail: { preflop: "rank", flop: "rank", turn: "rank", river: "rank" },
    },
    score: "high",
  },
  {
    id: "eclipse-color",
    name: "Eclipse Color",
    shortName: "Eclipse C",
    summary: "Community cards show only red or black until reveal.",
    detail: "The board exposes color pressure while hiding exact ranks and suits until the final reveal.",
    tags: ["visibility", "colors"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetail: { preflop: "color", flop: "color", turn: "color", river: "color" },
    },
    score: "high",
  },
  {
    id: "dark-river",
    name: "Dark River",
    shortName: "Dark R",
    summary: "The river card shows only its suit until reveal.",
    detail: "The first four board cards are normal, but the final river card keeps its rank hidden until reveal.",
    tags: ["visibility", "river"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetails: { river: { 4: "suit" } },
    },
    score: "high",
  },
  {
    id: "dark-flop",
    name: "Dark Flop",
    shortName: "Dark F",
    summary: "The flop stays face-down until turn.",
    detail: "No community cards are visible at flop; the board catches up at turn.",
    tags: ["visibility", "flop"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 0, turn: 4, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "hidden-turn",
    name: "Hidden Turn",
    shortName: "Hidden T",
    summary: "The turn card stays hidden until river.",
    detail: "The flop is visible, but the fourth board card is withheld until the river reveal catches up.",
    tags: ["visibility", "turn"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 3, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "confirm-flop",
    name: "Confirm Flop",
    shortName: "Confirm",
    summary: "The flop is hidden, then confirmed all at once on turn.",
    detail: "The table ranks preflop and flop without board cards, then the flop and turn appear together.",
    tags: ["visibility", "flop"],
    deal: {
      holeCards: 2,
      communityCards: 5,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 0, turn: 4, river: 5, reveal: 5 },
    },
    score: "high",
  },
  {
    id: "two-step-river",
    name: "Two-Step River",
    shortName: "2-Step",
    summary: "The river has two final cards; one waits until reveal.",
    detail: "A sixth board card is dealt, but only one of the two final river cards is visible before reveal.",
    tags: ["visibility", "river"],
    deal: {
      holeCards: 2,
      communityCards: 6,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 5, reveal: 6 },
    },
    score: "high",
  },
  {
    id: "random-replace",
    name: "Random Replace",
    shortName: "Replace",
    summary: "At turn, one visible board card is swapped for a fresh card.",
    detail: "The board mutates as the turn begins, forcing the table to re-evaluate earlier placements.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { turn: ["randomReplaceVisibleCommunity"] },
    score: "high",
  },
  {
    id: "cascade",
    name: "Cascade",
    shortName: "Cascade",
    summary: "The oldest visible board cards fade face-down as streets advance.",
    detail: "One more early community card becomes unknown at each board street, while reveal restores the true board.",
    tags: ["visibility", "board"],
    deal: {
      ...standardDeal,
      visibleCommunityCardDetails: {
        flop: { 0: "hidden" },
        turn: { 0: "hidden", 1: "hidden" },
        river: { 0: "hidden", 1: "hidden", 2: "hidden" },
      },
    },
    score: "high",
  },
  {
    id: "reversal",
    name: "Reversal",
    shortName: "Reverse",
    summary: "At river, the board reverses in place.",
    detail: "The same five community cards remain in play, but their displayed order flips when the river phase begins.",
    tags: ["event", "board"],
    deal: standardDeal,
    phaseEffects: { river: ["reverseCommunity"] },
    score: "high",
  },
  {
    id: "mirror-board",
    name: "Mirror Board",
    shortName: "Mirror",
    summary: "At the river, the board doubles into a primary row and a mirrored row.",
    detail: "Ten community slots fan out on river street, but scoring still uses the five primary cards — the mirror row is read-only theatrics.",
    tags: ["board", "mirror"],
    deal: {
      ...standardDeal,
      boardLayout: { kind: "dual", primary: 5, secondary: 5, secondaryRole: "mirror" },
      visibleCommunityCards: { lobby: 0, dealChoice: 0, preflop: 0, flop: 3, turn: 4, river: 10, reveal: 10 },
      scoreCommunityCards: 5,
    },
    phaseEffects: { river: ["mirrorCommunity"] },
    score: "high",
  },
  {
    id: "vault-card",
    name: "Vault Card",
    shortName: "Vault",
    summary: "A sixth community card waits in a vault lane until reveal opens it.",
    detail: "The main board fills normally through river while a separate vault slot stays empty; reveal exposes its hidden card alongside the five primary board cards.",
    tags: ["visibility", "reveal"],
    deal: {
      holeCards: 2,
      communityCards: 6,
      boardLayout: { kind: "dual", primary: 5, secondary: 1, secondaryRole: "vault" },
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 5, reveal: 6 },
    },
    score: "high",
  },
  {
    id: "phoenix-board",
    name: "Phoenix Board",
    shortName: "Phoenix",
    summary: "Every discarded third hole card rises back into a reveal-only vault row.",
    detail: "Each hand keeps two of three dealt cards through the streets; reveal opens a vault lane that shows every discard the table threw away.",
    tags: ["board", "discards"],
    deal: {
      holeCards: 3,
      keepCards: 2,
      communityCards: 5,
      boardLayout: { kind: "dual", primary: 5, secondary: 17, secondaryRole: "vault" },
      discardedCardsToCommunity: true,
      visibleCommunityCards: { lobby: 0, preflop: 0, flop: 3, turn: 4, river: 5, reveal: 22 },
    },
    score: "high",
  },
  {
    id: "flush-hunt",
    name: "Flush Hunt",
    shortName: "Flush",
    summary: "Hands rank by the largest same-suit cluster first.",
    detail: "Poker strength breaks ties, but suit density is the primary objective.",
    tags: ["objective", "suits"],
    deal: standardDeal,
    score: "flush",
  },
  {
    id: "straight-hunt",
    name: "Straight Hunt",
    shortName: "Straight",
    summary: "Hands rank by their longest rank run first.",
    detail: "Poker strength breaks ties, but connected cards define the table order.",
    tags: ["objective", "ranks"],
    deal: standardDeal,
    score: "straight",
  },
  {
    id: "pair-party",
    name: "Pair Party",
    shortName: "Pairs",
    summary: "Pairs, trips, and quads are the main scoring target.",
    detail: "The best multiplicity profile wins, with normal poker strength as the tiebreaker.",
    tags: ["objective", "ranks"],
    deal: standardDeal,
    score: "pairs",
  },
  {
    id: "red-shift",
    name: "Red Shift",
    shortName: "Red",
    summary: "Red cards are the primary scoring resource.",
    detail: "More hearts and diamonds rank higher; poker strength breaks close red counts.",
    tags: ["objective", "colors"],
    deal: standardDeal,
    score: "red",
  },
  {
    id: "black-ice",
    name: "Black Ice",
    shortName: "Black",
    summary: "Black cards are the primary scoring resource.",
    detail: "More clubs and spades rank higher; poker strength breaks close black counts.",
    tags: ["objective", "colors"],
    deal: standardDeal,
    score: "black",
  },
] as const;
